### ISSUE TITLE
Is Carthage mandatory?

### ISSUE THREAD

**Issue by pepejeria** [RxSwiftCommunity/RxFlow#1]
There is a run script that expect the user to have a carthage (`/usr/local/bin/carthage`) folder. The projects won't build because of this

**Comment by twittemb** [comment]
Hi @pepejeria 

Yes, to build the project you need to install Carthage to build the dependencies and Swiftlint to run the code analysis.

Are you familiar with these tools ?

**Comment by pepejeria** [comment]
No, but I can install them no problem. Would it be possible to have a future version that does not rely on Carthage?

**Comment by twittemb** [comment]
You can install those tools with brew (brew install carthage and brew install swiftlint)

The other solution would have been to use CocoaPods because Carthage and Swiftlint can be embedded inside pods. But unfortunately I cannot mix these 2 dependency managers 🙁.

**Comment by twittemb** [comment]
Hi @pepejeria, have I correctly answered your question ?

**Comment by pepejeria** [comment]
Yeah, this answer my question thank you. I guess that asking for not having to have Carthage would be a feature request for a separate ticket?

**Comment by twittemb** [comment]
I will close the issue then. I don't think it is possible to have both dependency managers at the same time. If you take a look at the other projects in the RxSwiftCommunity, Carthage is used a lot.

But you are welcome if you have a good Idea on this ! 👌

**Comment by orta** [comment]
FWIW: SwiftLint is a pod: https://github.com/realm/SwiftLint/blob/master/SwiftLint.podspec

**Comment by twittemb** [comment]
Hi @orta 

Yes that what I meant when I reply to @pepejeria: 
" _The other solution would have been to use CocoaPods because Swiftlint can be embedded inside à pod. But unfortunately I cannot mix these 2 dependency managers_ "

Thank you for accuracy :-)
