### ISSUE TITLE
carthage installation issue

### ISSUE THREAD

**Issue by Gurpartap** [RxSwiftCommunity/RxFlow#10]
With `github "RxSwiftCommunity/RxFlow"` in my path/to/myproject/Cartfile, `carthage update`[1] fails without any useful information in logs (both stdout and xcodebuild log file).

The solution was to `cd /path/to/myproject/Carthage/Checkouts/RxFlow/RxFlow && carthage update`[1]. After this, running `carthage update`[1] again in /path/to/myproject succeeded as expected.

It should not be ideally necessary for the developer to do a nested installation.

[1] `carthage update --platform iOS --configuration Release --no-use-binaries --cache-builds`

**Comment by ayoubkhayatti** [comment]
I'm not expert in Carthage, but that's because RxFlow target has it's own dependencies, while RxFlow is a dependency in RxFlowDemo, so have to `carthage install` in the frameworks target then in demo project.

**Comment by twittemb** [comment]
Hi @Gurpartap, thanks for your feedback. I'm going to take a look at that today and keep you informed.

**Comment by twittemb** [comment]
Hi @Gurpartap 

I have pushed a release 1.0.4. It should fix the Carthage issue.

I close this thread.

Thanks for the feedback.

**Comment by sirvon** [comment]
@ayoubkhayatti can you explain that..because i'm having a rough time getting library to build?
