### ISSUE TITLE
iOS 8.0 support? 

### ISSUE THREAD

**Issue by Jokemac** [RxSwiftCommunity/RxFlow#102]
Why does not support iOS8.0?
![image](https://user-images.githubusercontent.com/16797357/51361148-95006f00-1b09-11e9-80cf-5ca603156224.png)

**Comment by twittemb** [comment]
Hi @Jokemac 

Usually it is a good practice to support the 2 last major versions of iOS: 12 and 11. RxFlow supports iOS 9.0.

It represents the very large majority of active devices (More than 99%).

**Comment by Jokemac** [comment]
@twittemb 
But now my company project has to support iOS 8.0 at the minimum, and I want to use RxFlow to improve my project.

**Comment by MortyMerr** [comment]
@Jokemac why can't u just fork it?

**Comment by Jokemac** [comment]
@MortyMerr 
So I just fork, then modify s.ios.deployment_target = "9.0" to become "8.0", can I use it normally?

**Comment by Jokemac** [comment]
@twittemb @MortyMerr 
OK, thank you
