### ISSUE TITLE
TabBarController

### ISSUE THREAD

**Issue by seyhagithub** [RxSwiftCommunity/RxFlow#106]
I got problem with tab bar controller. when i use only one tab it works fine but when i use two tabs the object viewmodel  in viewcontroller is nil. The problem happens when i migrate from 1.x.x to 2.0.0.
Here my code:

AppDelegate
```
let dashboardFlow = DashboardFlow(dependency: DependencyRegistry())
    
    guard let window = self.window else { return true }
    
    Flows.whenReady(flow1: dashboardFlow, block: { [unowned window] (flowRoot) in
      window.rootViewController = flowRoot
      window.makeKeyAndVisible()
    })
    self.coordinator.coordinate(flow: dashboardFlow, with: OneStepper(withSingleStep: AppStep.dashboard))

```

DashboardFlow

```
fileprivate func navigateToDashboard() -> FlowContributors {
    let homeFlow = HomeFlow(dependency: dependency)
    let secondFlow = SecondFlow(dependency: dependency)
    
    Flows.whenReady(flow1: homeFlow, flow2: secondFlow) { [unowned self] (root1: UINavigationController, root2: UINavigationController) in
      
      
      let homeItem = UITabBarItem(title: "Home", image: UIImage(named: "home"), selectedImage: nil)
      
      let homeItem2 = UITabBarItem(title: "Second", image: UIImage(named: "home"), selectedImage: nil)
      
      root1.tabBarItem = homeItem
      root2.tabBarItem = homeItem2
      
      self.rootViewController.setViewControllers([root1, root2], animated: false)
    }
    
    return .multiple(flowContributors: [
      .contribute(withNextPresentable: homeFlow, withNextStepper:OneStepper(withSingleStep: Homestep.home)),
      .contribute(withNextPresentable: secondFlow, withNextStepper: OneStepper(withSingleStep: Homestep.home))
      ])
  }
```

View Controller

```
class ViewController: UIViewController {
  
  var viewModel: ViewModel!

  override func viewDidLoad() {
    super.viewDidLoad()
    
    print("ViewModel \(viewModel.title)")
   
  }
}


```

viewModel.title is nil

**Comment by vvghost1** [comment]
.contribute(withNextPresentable: secondFlow, withNextStepper: OneStepper(withSingleStep: Homestep.home))

Is `Homestep.home` in that line mistake? Looks strange. If not, can you share code of SecondFlow?

**Comment by twittemb** [comment]
Hi @seyhagithub 

Can you share the code of your first and second flows because I can't figure out how the ViewModels are created with your example ?

Thanks.

**Comment by seyhagithub** [comment]
Hi @twittemb, @vvghost1 

```
class SecondFlow: Flow {
  
  var root: Presentable {
    return self.rootViewController
  }
  
  let rootViewController = UINavigationController()
  
  let dependency: DependencyRegistry
  
  init(dependency: DependencyRegistry) {
    self.dependency = dependency
  }
  
  
  func navigate(to step: Step) -> FlowContributors {
    guard let step = step as? Homestep else { return .none }
    switch step {
    case .home:
      return navigateToHome()
    }
  }
    
    fileprivate func navigateToHome() -> FlowContributors {
     let viewController = dependency.resolver.resolve(SecondViewController.self)!
      self.rootViewController.pushViewController(viewController, animated: true)
     return .one(flowContributor: .contribute(withNextPresentable: viewController, withNextStepper: viewController.viewModel))
  }
}
```
Thank in advance.

**Comment by vvghost1** [comment]
@seyhagithub you need to look inside `DependencyRegistry` and search if you forgot to setup `ViewController`'s `viewModel` property after creation. As we can see you are not setting up it here, and looks like your problem is not related to RxFlow

**Comment by seyhagithub** [comment]
@vvghost1 thank for  this comment. My `DependencyRegistry` is swinject. It will resolve related object. First thing first, i think like this too.
```
class MyAssembly: Assembly {
  func assemble(container: Container) {
    
    container.register(ViewModel.self) { _  in
      return ViewModel()
    }.inObjectScope(.graph)
    
    container.register(ViewModel2.self) { _  in
      return ViewModel2()
      }.inObjectScope(.graph)

container.register(ViewController.self) { resolver  in
      let storyboard = UIStoryboard.init(name: "Main", bundle: nil)
      let temp = storyboard.instantiateViewController(withIdentifier: "ViewController")
      let viewController = temp as!  ViewController
      viewController.viewModel = resolver.resolve(ViewModel.self)!
      return viewController
    }
    
    container.register(SecondViewController.self) { resolver  in
      let storyboard = UIStoryboard.init(name: "Main", bundle: nil)
      let temp = storyboard.instantiateViewController(withIdentifier: "SecondViewController")
      let viewController = temp as!  SecondViewController
      viewController.viewModel = resolver.resolve(ViewModel2.self)!
      return viewController
    }
  }
}

```

**Comment by vvghost1** [comment]
@seyhagithub maybe `title` property in `ViewModel`/`ViewModel2` is `nil` then? :D

**Comment by seyhagithub** [comment]
@vvghost1 `ViewModel / ViewModel2` is nil not title
```
class ViewModel: Stepper {
  var steps = PublishRelay<Step>()
  let title = "Hello"
}
```

**Comment by vvghost1** [comment]
@seyhagithub I dont use storyboard for a while for now, but as I remember `instantiateViewController` method forced `viewDidLoad` to execute, and at that step `viewModel` property didn't setted up yet. If so, you can move your work with `viewModel` to `viewWillAppear`, for example

**Comment by seyhagithub** [comment]
@vvghost1 My problem is that `viewModel` is nil even we move this property to another event in `ViewController`

**Comment by vvghost1** [comment]
@seyhagithub can you share sample project with this behavior?

**Comment by beretis** [comment]
I had simular problem, I use my own custom implementation of tab bar using ContainerViewController, and I had problem that after I changed tabs, when I came back to the previous tab, FlowCoordinator didn't respond to my Stepper (it got dealocated). I spent few hours debuging and found out that this code is the reason: 
```
    /// Rx observable, triggered when the view is being dismissed
    public var dismissed: ControlEvent<Bool> {

        let dismissedSource = self.sentMessage(#selector(Base.viewDidDisappear))
            .filter { [base] _ in base.isBeingDismissed }
            .map { _ in false }

        let movedToParentSource = self.sentMessage(#selector(Base.didMove))
            .filter({!($0.first is UIViewController)})
            .map { _ in false }

        return ControlEvent(events: Observable.merge(dismissedSource, movedToParentSource))
    }
```
specifically movedToParentSource. I implemented containerViewController according apple [documentation](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html) / Listing 5-3Transitioning between two child view controllers.

Maybe even system TabBar has similar issue. I wanted to ask, will I brake something if I comment out this code?

**Comment by seyhagithub** [comment]
@vvghost1 here is my[ sample project ](https://github.com/seyhagithub/TestRxFlow). thank for your time

**Comment by vvghost1** [comment]
@seyhagithub the issue is in entry point of your app, it is `ViewController` in Main.storyboard. Your app trying to instantiate `ViewController` as described by entry point just after `didFinishLaunchingWithOptions`, this is common process, and FlowCoordinator just don't have chance to take control of window. The solution is easy, just make any safe placeholder entry point. I love solution in RxFlow sample app: in info.plist change value for key `UIMainStoryboardFile` from `Main` to `LaunchScreen`.

**Comment by seyhagithub** [comment]
@vvghost1 wow that's is really useful answer. Thank @vvghost1 it works now.

**Comment by snowtema** [comment]
Hello!
How I can create two flows with tab bar which has three tabBarButtoItem's? Thanks!

**Comment by twittemb** [comment]
Hi @snowtema 

Can you elaborate a little bit please ?

thanks

**Comment by snowtema** [comment]
Hi @twittemb, thanks for the quick response!

I want to create something like these:
<img width="499" alt="Снимок экрана 2019-03-20 в 1 34 06" src="https://user-images.githubusercontent.com/24715092/54646502-48f18c80-4ab0-11e9-8bbd-657c55c49eee.png">

But a Plus button hasn't their own flow, because of its simple modal view controller.

**Comment by snowtema** [comment]
I mean, can I create these button from standard RxFlow mechanism without any magic code, f.e. adding UIButton above tabBarController.tabBar?

**Comment by supervtb** [comment]
@twittemb  Hi, I have some issue with tabbar, deep link and presented view controller, maybe you could explain right way for flow?
case: User open main screen, choose 2 tab bar item (for eg), then in this place open next view controller (with present function), then user go to the safari and open deeplink (after it app have to switched to the 1 tab and push view controller)
But instead. App switching to the 1 tab in tabbar, pushing VC but I see latest presented screen still and when I try to close it - nothing happening because RxFlow lost link to presented vc (link to vc is nil).

Or maybe you could share more detailed instruction about deep linking and right way for implementation deep links?

**Comment by twittemb** [comment]
Hi @supervtb 

Here is an attempt to handle deep links with RxFlow -> https://github.com/RxSwiftCommunity/RxFlow/pull/147

 I would be interested in your feedback if you could try this branch against your code base.

Thanks.

**Comment by wintermoon9** [comment]
@beretis How did you end up fixing this ? Having the same problem with a custom tab bar.

**Comment by wintermoon9** [comment]
Does anyone know about the above ^ is this project alive ?

**Comment by beretis** [comment]
@wintermoon9 I did fix it, let me find the solution and help you.

**Comment by nflahavan** [comment]
Should the definition of `rxDismissed` be `self.rx.dismissed.filter { $0 }.map { _ -> Void in return Void() }.take(1).asSingle()`?
