### ISSUE TITLE
Deinit FlowCoordinator

### ISSUE THREAD

**Issue by lm2343635** [RxSwiftCommunity/RxFlow#109]
How can I deinit the flows instance of coordinator or the coordinator itself directly.

I mean I want to start a new flow from AppDelegate from a new coordinator and discard the old flows in the old coordinator.

In fact, when I tried to invoke the following method,

```Swift
coordinator.coordinate(flow: flow, with: OneStepper(withSingleStep: step))
```

the new flow can be navigated from the root window.
**However**, the memory of the old view controllers and old flows cannot be recycled.

![screen shot 2019-02-25 at 11 39 28](https://user-images.githubusercontent.com/9463655/53310919-1eb61000-38f2-11e9-90d4-31b3e906f0b1.png)

**Comment by twittemb** [comment]
Hi @lm2343635 

I'm not sure what you are trying to achieve here. FlowCoordinator is not meant to be deallocated/re-instanciated as it is supposed to handle the App navigation during its whole lifecycle.

However, a Flow is deallocated whenever a .end FlowContributor has been emitted or whenever its root viewController has been dismissed.

Could you tell us more about your use case ?

**Comment by lm2343635** [comment]
For example, I have a flow named `SigninFlow` which contains view controllers about `sign in` and `sign up`.
A device send requests with an access token after signing in.
When a user tries to change password from one of his device, the app server will invalidate the access token in the other devices of him.
I hope to invoke the `SigninFlow` from any view controller, and show the sign in view controller, when the access token becomes invalid.

**Comment by lm2343635** [comment]
If possible, I hope to control back to the first view controller from the current view controller with a single line of code.

**Comment by twittemb** [comment]
Please have a look at the demo app because it does something very similar. The flow listens for the connected state of the user, and when it changes to "not connected" it automatically displays a login screen.

**Comment by lm2343635** [comment]
Hi @twittemb,
Thanks for your replying.
I am sorry that I cannot show the app to you because it is a private project.
As what you said in your last comment, I just want to display a login screen I a user changes to the unlogin state, and I hope to back to the root view controller of the app from anywhere with a single line of code.

**Comment by twittemb** [comment]
Please take a look at the AppFlow in the demo app:

```swift
class AppStepper: Stepper {

    let steps = PublishRelay<Step>()
    private let appServices: AppServices
    private let disposeBag = DisposeBag()

    init(withServices services: AppServices) {
        self.appServices = services
    }

    var initialStep: Step {
        return DemoStep.dashboardIsRequired
    }

    /// callback used to emit steps once the FlowCoordinator is ready to listen to them to contribute to the Flow
    func readyToEmitSteps() {
        self.appServices
            .preferencesService.rx
            .isOnboarded
            .map { $0 ? DemoStep.onboardingIsComplete : DemoStep.onboardingIsRequired }
            .bind(to: self.steps)
            .disposed(by: self.disposeBag)
    }
}
```

The flow's Stepper reacts to the onboarding state of the user to automatically trigger a step that will be interpreted by the AppFlow to display the Onboarding screens.

**Comment by twittemb** [comment]
Hi there,

as there is not much activity on this thread, I will close the issue. Feel free to reopen it if you think this is relevant
