### ISSUE TITLE
Flow change from a presented viewcontroller create memory leak

### ISSUE THREAD

**Issue by sulaiman-mlbd** [RxSwiftCommunity/RxFlow#110]
If you present a UIViewController and from that screen you make a step which change flow will create a memory leak by holding the NavigationController with full stack of ViewController within it. That flow is deallocated but the navigation controller and other view controller still exists on memory.

**Comment by twittemb** [comment]
Hi @sulaiman-mlbd 

Without more context I won't be able to help. Can you share some code for instance ?

**Comment by sulaiman-mlbd** [comment]
![Screenshot 2019-03-11 at 2 47 37 PM](https://user-images.githubusercontent.com/47207931/54110855-a9c3f980-440c-11e9-9ca5-d6e683cd5ef1.png)
See the screenshot, if i present a viewcontroller like `self.rootViewController.present(signInSelectViewContorller, animated: true, completion: nil)` like this on and change the flow from `SignInSelectViewModel` will create a memory leak. I have fixed my issue by using this `self.rootViewController.pushViewController(signInSelectViewContorller, animated: false)` this one. But i think that you should know about the issue so that other people shall not face the same problem. If you need further details, i can provide you

**Comment by twittemb** [comment]
Hi @sulaiman-mlbd 

If I get this right, you are trying to present the SignInSelectViewController modally and then you want to move on to another flow.

Don't you want to dismiss the modal screen before navigating to another flow ?

**Comment by sulaiman-mlbd** [comment]
Yes. It was my requirement
