### ISSUE TITLE
The best practice to pass data backward

### ISSUE THREAD

**Issue by vldalx** [RxSwiftCommunity/RxFlow#111]
Let's say I have a `SomeViewModel` and a `SomePickerViewModel`.
For example, the `ProfileViewModel` needs a photo from the iPhone Photo library, so it emits a step to open the `AwesomePhotoPicker` screen. If the user chooses an image the one should be passed to the `ProfileViewModel`.
What is the best way to pass any data to the previous step (previous ViewModel)?

**Comment by twittemb** [comment]
hi @vldalx 

The way I do it is:
- define a step that has a associated value, a closure that takes the result you want to pass as a parameter
- in your stepper, when you trigger this step, you pass the closure defining the behavior you want to apply when receiving the result
- in the AwesomePhotoPicker, you store the closure (given to you by the step/flow) and execute it with the good parameter when you are done

Just pay attention to the retain cycles as this involves closures potentially capturing self for instance.

**Comment by vldalx** [comment]
Hi @twittemb,

Thank you for the answer, you got me thinking about it.

I have an idea to change your approach a little bit. The idea is:
Instead of the closure, I would use an `AnyObserver<SomeData>`.
The stepper (`ProfileViewModel`) has a `PublishSubject` instance and passes `PublishSubject.asObserver()` as the associated value when triggering the step. The stepper is subscribed to the `PublishSubject` instance. 
The `AwesomePhotoPickerViewModel` emits the data from any observable to the `AnyObserver<SomeData>`.
What do you think about it?


Because my app adheres Dependency injection pattern I've implemented another approach based on [Caliburn.Micro EventAggregator](https://caliburnmicro.com/documentation/event-aggregator).
I use [Swinject](https://github.com/Swinject/Swinject) to follow DI.

``` Swift
let container = Container()

container.register(ViewModel.self) { _ in
    .init()
}.inObjectScope(.weak)

container.register(DataPickerHandler.self) {
    $0.resolve() as ViewModel
}

container.register(PickerViewModel.self) {
    .init(pickerHandler: $0.resolve())
}

protocol DataPickerHandler {
    var pickedData: PublishSubject<SomeData> { get }
}

class ViewModel: Stepper, DataPickerHandler {
    let pickedData = PublishSubject<SomeData>()

    // subscription to pickedData
}

class PickerViewModel: Stepper {
    let pickerHandler: DataPickerHandler
    init(pickerHandler: DataPickerHandler) {
        self. pickerHandler = pickerHandler
    }

    /// emitting data to pickerHandler.pickedData
}
```

**Comment by twittemb** [comment]
👍 Passing an observer is something I had also in mind. Thanks for sharing with every one.

May I close the issue ?

**Comment by vldalx** [comment]
Yes, you may close. Thanks.
