### ISSUE TITLE
Stepper has no effect in basic test implementation

### ISSUE THREAD

**Issue by TheFalseFriend** [RxSwiftCommunity/RxFlow#112]
Hi @twittemb,

I'm looking to try out RxFlow (looks very promising). To this end I've created an extremely simple, two-flow app (each flow having a single screen defined in separate storyboards). Each flow-screen is a plain-old-UIViewController. There is a button on the initial flow-screen; when the user taps this I want to send them to the second flow (no further navigation required after this point, just trying to get the most basic of actions wired up for now).

I've read the docs, perused the demo app, and examined the source code - but I just cannot seem to get this simplest of configurations working. I currently have my code wired up as such [here](https://gist.github.com/TheFalseFriend/f7de0246b1e4e4fc37d6ca3400d57ef3) (general wiring) and [here](https://gist.github.com/TheFalseFriend/ca62b331c1b38b8b4c6ba201f8c6741a) (app delegate bootstrap).

As for the actual invocation of the SecondFlowRequired step: the view controller for the first flow's single screen has an instance of AppStepper set at creation time (i.e. `var stepper = AppStepper()` in UIViewController class body). I have an IBAction wired up to the button on the home screen that calls `self.stepper.toSecondFlow()`. 

While the app builds and runs, and presents the first screen/(flow?), absolutely nothing happens when I tap the IB-wired button that should send me to the other flow I've defined. It's like the stepper is just having no effect, failing silently.

Nobody seems to have had similar issues starting out so I _must_ be missing something here (I'm new to Swift, and iOS development in general). 

Any help you can give much appreciated!

Best

**Comment by DhbStudy** [comment]
You write
self.coordinator.coordinate(flow: appFlow, with: AppStepper())
then I think you can't init another AppStepper() in your UIViewController. You can change your struct.
