### ISSUE TITLE
Stepper broken when present with custom model presentation

### ISSUE THREAD

**Issue by mumensh** [RxSwiftCommunity/RxFlow#114]
Hi,

I've found a bug with RxFlow, if a step is done with a custom presentation, when dismissing it the steps.accept won't work

Here is how I present the viewController
`let viewModel = ViewModel()`
`let viewController = ViewController.loadFromStoryboard(storyboardNameOrNil: "Main")`
`viewController.viewModel = providerViewModel`
`viewController.modalPresentationStyle = .overFullScreen`
`self.rootViewController.present(providerLocationViewController, animated: true)`

When dismissing it, the presenting view controller steps won't work any more unless it's allocated again (by ending the flow and initiate it again)

**Comment by twittemb** [comment]
@mumensh 

Thanks for the feedback. I'm gonna try your use case on the demo app and I'll get back to you ASAP.

**Comment by twittemb** [comment]
@mumensh 

what version of RxFlow are you using ?

in the snippet you provided, I can see that you instantiate a ViewModel but set the viewModel property with another one (providerViewModel), is this an error in your snippet ?

When you speak about "custom presentation", is it just about this line `viewController.modalPresentationStyle` ?

When a try to present a modal screen in the demo app (like the About screen in the WishlistFlow) with this kind of modalPresentationStyle, then when dismissed, the root screen still reacts to steps.

Could you provide the code of the entire App or at least of the Flow please ?

**Comment by mumensh** [comment]
Hi @twittemb, Thank you for your quick reply.

I'm using RxSwift version 2.0.0

I've tried to build a demo to show you the case, please forgive the unorganised code.

to produce the issue, run the demo, open the second tab, then tap on an image then drag the presented image using the pan gesture, make your first try fail (by dragging the image to it's location then make the second attempt of dismissing work, the steps won't work anymore

[motionBug 2.zip](https://github.com/RxSwiftCommunity/RxFlow/files/3063013/motionBug.2.zip)

**Comment by twittemb** [comment]
Hi @mumensh 

I've tried your demo app and I can't reproduce the issue. Can you more specific the way to make it happen.


what I've done:
- launch the app
- go to 2nd tab
- tap on first image -> a new ViewController pops up
- tap and pan the image at its original location -> ViewController is not dismissed
- tap and pan the image to make the ViewController being dismissed -> ViewController is dismissed
- go to 1st tab and click an image -> a new ViewController pops up
- tap on 1st tab -> the navigation stack goes back to root ViewController

What am I missing ?

**Comment by mumensh** [comment]
@twittemb Thank you for your reply, I've checked the demo and indeed the issue does not exist, but in my project it the issue is their, so, I've did some debugging and after a while I've notice that a change made in another library "Motion" and that change fixed the issue.

The issue was rxVisible was called and set to `false` when trying to dismiss a view controller with `modalPresentationStyle` equal to `.overFullScreen`, when it's failed there is a piece of code that was causing the presenting view controller to be not visible, which lead to steps not working (because it's viewController is not visible, which is fine behavior), note that when change the model presentation to `.overFullScreen` or `.overCurrentContext`, the `viewDidAppear` and `viewDidDisappear` will not called on the presented controller.
