### ISSUE TITLE
Help on UIStateRestoring

### ISSUE THREAD

**Issue by leeelton** [RxSwiftCommunity/RxFlow#116]
I'm currently working on a mini-project with RxFlow and have run into a blocker when trying to implement UIStateRestoring.

This is done through implementing `restorationIdentifiers`, `restorationClasses`, and `encodeRestorableState` / `decodeRestorableState` on ViewControllers. With RxFlow, ViewControllers become ignorant of their navigation hierarchy which is managed by the `FlowCoordinator` and `FlowContributors`. 

This presents a problem with typical state restoration because the standard `UIStateRestoring` API doesn't look like it has a well-defined place to setup Flows.

Do you have any recommendations on how to work around this or implement `UIStateRestoring`?

**Comment by twittemb** [comment]
Hi there,

honestly, I've never used `UIStateRestoring`. Would you be able to provide a sample of your app ?

**Comment by leeelton** [comment]
https://github.com/leeelton/app-architecture/tree/master/Recordings-MVVM-C

it's a fork of a repo that I was rewriting to learn more about RxFlow. I've given it some thought and this is most likely just a limitation of the UIStateRestoration API. It looks like the best solution would most likely to implement my own state restoration, saving objects to Core Data or something similar to recreate the Flow objects and View Controllers.

I'll go ahead and mark this as closed.
