### ISSUE TITLE
Logout and deinit child flows

### ISSUE THREAD

**Issue by MasterWatcher** [RxSwiftCommunity/RxFlow#122]
Hi! First of all, thank you for such a great navigation framework.

I use RxFlow in my app and I would like to logout from an app by changing root view controller and deinit whole stack of flows (with theirs view controllers). Logout can be triggered from any part of the app (invalid access token), so `.end (forwardToParentFlowWithStep: Step)` is not an option. RxFlowDemo doesn't illustrate such case. How can I accomplish it?

**Comment by MortyMerr** [comment]
Hi, I think that the proper solution would be recreate whole RxFlow stack:
```swift
extension AppDelegate {
  func unaunauthorize() {
      self.coordinator = FlowCoordinator()
      let appFlow = AppFlow(withWindow: window)
      self.coordinator.coordinate(flow: appFlow, with: OneStepper(withSingleStep: Steps.landing))
  }
```
I wonder if @twittemb has better option

**Comment by twittemb** [comment]
Hi @MasterWatcher 

Is it an option for you to have a global AppStep.logout that can be emitted by any stepper and handled by any flow ? 

In each flow you could react to this step by returning a .end (forwardToParentFlowWithStep: Step) flowContributor in cascade to the root Flow. In the root Flow you could react to this step by replacing the UIWindow's root VienController by a new one. It supposes that you pass the UIWindow as an init parameter to the root Flow.

To mutualize logout code between Flows you can play with protocol default implementation (your flows could conform to a 'CanLogout' protocol)

Does it help ?
