### ISSUE TITLE
What is warp?

### ISSUE THREAD

**Issue by isaac-weisberg** [RxSwiftCommunity/RxFlow#124]
https://github.com/RxSwiftCommunity/RxFlow/blob/eeb06aff40e7e5a06274d86f4193102612e2baa2/RxFlow/Presentable.swift#L17

I've been browsing the source code and got just a tiny bit confused, you meant Flow, what, was it renamed at some point?

**Comment by twittemb** [comment]
Hi @isaac-weisberg 

It was from a previous naming in the project. I fixed it.

Thanks.
