### ISSUE TITLE
Update README.md with SPM Installation guide

### ISSUE THREAD

**Issue by MortyMerr** [RxSwiftCommunity/RxFlow#127]

**Comment by rynecheow** [comment]
@twittemb Are we planning to do a release anytime soon?

**Comment by MortyMerr** [comment]
@twittemb could u please provide soft estimates about 2.5.0 release?
Also what do you think about removing 1.x.x -> 2.x.x migration guide? Or at least moving it to separate .md file. It might be terrifying for new users to see this big breaking changes list. Old users had a lot of time to migrate :)

**Comment by twittemb** [comment]
I think I Will release a 2.5.0 this weekend

**Comment by MortyMerr** [comment]
Resolved
