### ISSUE TITLE
Pass data between modally presented ViewController

### ISSUE THREAD

**Issue by sree127** [RxSwiftCommunity/RxFlow#149]
First of all, thanks a lot of creating this awesome library and kudos to all the maintainers 💪

#### Problem
I have been scratching my head over the past few days to implement a clean way to pass data between a modally presented ViewController and the parent controller. 

#### Sample code

In `ABCFlow`

    if let step = step as? ABCStep {
      switch step {
      case .addressInput(selectedCountry: String?):
        return navigateToAddressInputScreen()
      case selectCountry:
        return navigateToSelectCountryScreen()
      }
    }
    
    func navigateToAddressInputScreen(selectedCountry: String?) {
		navigationController.setViewController([addressInputVC])
    }
    
    func navigateToSelectCountryScreen() {
    	navigationController.present(selectCountryVC)
    }

Now, `selectCountry` is a modally presented ViewController and upon selecting a country, it emits the step `ABCStep.addressInput(selectedCountry: "Germany")`

#### Synopsis
Now the issue is, `addressInputVC` is already in the navigation stack and I couldn't find a nice way to pass the `selectedCountry` to `addressInputVC` other than calling the `navigateToAddressInputScreen(selectedCountry: String?)` thereby reloading/setting the viewcontroller again. 

What do you think would be the best way to pass data between a modally presented viewcontroller to its parent viewcontroller without re-presenting it? 

PS: I'm not a big fan of storing a global ViewController variable in the Flow and checking if the ViewController is already presented or not. :)

Thanks in advance

**Comment by twittemb** [comment]
Hi @sree127 

Thanks for your kind words.

Usually, if I want to retrieve a data from a modal I use a step with a callback closure inside.

Let’s say we have a root ViewController that wants to display a modal. The VC can emit a step with a closure as a parameter: AppStep.modalIsRequired(block: { output -> print(output) }).
The AppStep.modalIsRequired definition is:

enum AppStep {
    case modalIsRequired(block: (String) -> Void)
}

You will receive the step in the Flow. There you can instantiate your modal and give it the block closure.

Inside the modal ViewController, you can call the block with the good parameter when it is necessary and then trigger a new Step to dismiss it: AppStep.modalHasFinished. In the Flow you just have to dismiss the modal.

Does it make sense ?

**Comment by sree127** [comment]
Hi @twittemb,

Yessss, makes total sense. That should work :) Thanks a lot for the tip 👍
