### ISSUE TITLE
Please document memory management

### ISSUE THREAD

**Issue by kean** [RxSwiftCommunity/RxFlow#152]
Hi, It would be fantastic to add a section in the documentation regarding memory management. For example, it is not entirely clear whether `FlowCoordinator` retains its contributors or parts of the contributors (presentable? stepper?) and, if yes, when they get deallocated. Is there any difference when the presentable is a `Flow`?

**Comment by wintermoon9** [comment]
I'm also wondering about this because my app is experiencing quite large memory leaks with RxFlow. Is this project alive??

**Comment by twittemb** [comment]
Hi there,

Yep the project is alive :-)

We are using RxFlow is several production app and we are not experiencing memory leaks. Can you tell me a bit more about your issues ?

Thanks.
