### ISSUE TITLE
CompositeStepper not calling InnerSteppers readyToEmitSteps

### ISSUE THREAD

**Issue by nflahavan** [RxSwiftCommunity/RxFlow#153]
I'm using `CompositeStepper` to combine my custom `Stepper` with another `Stepper`. I assumed in the `CompositeStepper` `readyToEmitSteps()` method my custom `Stepper`'s `readyToEmitSteps()` method would be called. This is not the case.

Is this intentional, and if so why? If not, would you be open to a PR to loop through a `CompositeStepper`'s `innerSteppers` and call their `readyToEmitSteps()` methods at the end of `CompositeStepper`'s `readyToEmitSteps()`?

**Comment by twittemb** [comment]
great thanks a lot. I'll try to review in the coming days.

**Comment by twittemb** [comment]
I've reviewed the PR. I have a minor comment.

I close this issue, since it is being addressed.

Thanks.
