### ISSUE TITLE
Something strange happening in ios14

### ISSUE THREAD

**Issue by rickrvo** [RxSwiftCommunity/RxFlow#156]
I have the following code which was working in ios 13:

```
func replaceWindowRootWith(flow: Flow, step: Step, fadeAnimation: Bool = true, addDelay: Bool = false) -> FlowContributors {
        Flows.whenReady(flow1: flow) { [weak self] root in
            root.hero.isEnabled = true
            root.hero.modalAnimationType = fadeAnimation ? .fade : .none
            if let currentRoot = self?.window?.rootViewController {
                let delay = addDelay ? 0.2 : 0
                DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
                    print("REPLACING - \(step.self)")
                    Hero.shared.cancel(animate: false)
                    currentRoot.hero.replaceViewController(with: root)
                }
            } else {
                self?.window?.rootViewController = root
                self?.window?.makeKeyAndVisible()
            }
        }
        return .one(flowContributor: .contribute(withNextPresentable: flow,
                                                 withNextStepper: OneStepper(withSingleStep: step)))
    }
```

the code inside DispatchQueue.main.asyncAfter is never fired. If I take out the dispatchqueue and run it normally inside the whenReady closure the print("REPLACING - \(step.self)") gets printed.

I tried lots of combinations and it worked once! but then I run again and it failed again... the changes I made to work was to change 
`Flows.whenReady(flow1: flow) { [weak self] root in`
to 
`Flows.use(flow when: .ready) { [unowned self] root in`
then I changed 
`currentRoot.hero.replaceViewController(with: root)`
to
`currentRoot.heroReplaceViewController(with: root)`

this worked once but now I can't get any transition.

Anyone with the same issue?

**Comment by fedapollo** [comment]
I had the same issue when update my xcode today
