### ISSUE TITLE
unknown dependency 'RxCocoa' in target 'RxFlow'

### ISSUE THREAD

**Issue by sukhanovevgeniy96** [RxSwiftCommunity/RxFlow#158]
<img width="429" alt="Screenshot 2020-10-01 at 12 09 09" src="https://user-images.githubusercontent.com/22646611/94790410-eb493a80-03de-11eb-9bfe-1bf95a9500d0.png">

I suppose it happened after had moved to swift-tools-version:5.3. Everything OK on branch feature/swift-5-3

**Comment by twittemb** [comment]
Hi

Have you tried the last release 2.10.0 ?

**Comment by sukhanovevgeniy96** [comment]
> Hi
> 
> Have you tried the last release 2.10.0 ?

Yes, the same issue

**Comment by twittemb** [comment]
What dependency manager are you using ?

**Comment by sukhanovevgeniy96** [comment]
I made an example of my issue. I created empty swift package and added RxFlow
https://github.com/sukhanovevgeniy96/DemoRxFlow

I used Xcode Version 12.0.1 (12A7300) and swift-tools-version:5.3

**Comment by sukhanovevgeniy96** [comment]
https://github.com/RxSwiftCommunity/RxFlow/pull/159

**Comment by twittemb** [comment]
This is merged. Thanks a lot.

**Comment by onsissond** [comment]
> This is merged. Thanks a lot.

@twittemb Could you added new tag for fetching this changes?
