### ISSUE TITLE
`Reactive+UIViewController`'s `dismissed` event is retaining the view controller

### ISSUE THREAD

**Issue by BenMaer-Parkwood** [RxSwiftCommunity/RxFlow#160]
In `Reactive+UIViewController.swift`, we have event `var dismissed: ControlEvent<Bool>`. Using this event ends up retaining the view controller that `.rx` is called on. This means that if this `.rx.dismissed` is subscribed to on a UIViewController, and the subscription isn't killed on the event call, the vc will never get released from memory.

Inside the body of `dismissed`, we have the following line:
`.filter { [base] _ in base.isBeingDismissed }`

By using `[base]`, the `base` variable ends up getting retained by this closure, which in this case is the UIViewController.

I believe the reason this doesn't currently cause any issues in RxFlow, is because it's only use once in `rxDismissed`, which adds `.asSingle()`, who knows to kill subscriptions once they've fired an event.

I still think it's worth preventing the retain in the first place, since otherwise RxFlow is exposing code that, if used, can lead to substantial memory leaks.

**Comment by BenMaer-Parkwood** [comment]
@twittemb Should I close this issue now that the PR is merged?

**Comment by twittemb** [comment]
Yes I will close it.

Thanks for your contribution.
