### ISSUE TITLE
Flow.rxVisible never emits `true` event when pushing view controller without animations

### ISSUE THREAD

**Issue by unreg-rea** [RxSwiftCommunity/RxFlow#163]
Hi @twittemb, 

Thank you for your great library. I've had a problem when applying RxFlow in my project. Whenever I push a view controller into navigation stack without animation, I cannot emit any further steps. 

This is my navigation code:
`            Flows.use(myFlow, when: .created) { [unowned self] (root) in
                // TODO: animate = false not working??
                self.navigationController?.pushViewController(root, animated: false)
            }
`
After debugging I found the problem is stepStream is permanently paused because rxVisible of myFlow is never emits `true` event. 

With animation enabled it is OK. Anyone with the same issue?

**Comment by sree127** [comment]
Have you tried with `Flows.use(myFlow, when: .ready)`
