### ISSUE TITLE
Coordinator navigate(to: ) does not override initialStep

### ISSUE THREAD

**Issue by MatrixSenpai** [RxSwiftCommunity/RxFlow#167]
For the main/initial flow, I've set the `initialStep` property to what the entry point to my app should be. However, the app may be opened through a share extension. When that is the case, using `coordinator.navigate(to: )` does _not_ override the initial step, and said step opens. This _only_ occurs if the app is not already running. If it's already open, the extension shares and opens as expected.

Here's my SceneDelegate:
```swift
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let scene = (scene as? UIWindowScene) else { return }
        
        window = UIWindow(windowScene: scene)
        
        let flow = AppFlow()
        Flows.use(flow, when: .created) { [weak window] root in
            window?.rootViewController = root
            window?.makeKeyAndVisible()
        }
        
        coordinator.rx.willNavigate.subscribe(onNext: { args in
            print("WN \(args.0) -> \(args.1)")
        }).disposed(by: bag)
        coordinator.rx.didNavigate.subscribe(onNext: { args in
            print("DN \(args.0) -> \(args.1)")
        }).disposed(by: bag)
        
        coordinator.coordinate(flow: flow, with: flow.stepper)
    }

    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        if let url = URLContexts.first?.url {
            switch url.scheme {
            case "livetl-translate":
                let id = url.path.replacingOccurrences(of: "/", with: "")
                coordinator.navigate(to: AppStep.view(id: id))
            default: break
            }
        }
    }
```

The stepper is simply the steps and initialStep property, nothing fancy happening

**Comment by twittemb** [comment]
Hi @MatrixSenpai 

If I understand correctly:

- if the app is already running: the `coordinator.navigate(to:)` works fine, and the navigation occurs thanks to the AppStep.view(id:) step
- if the app is not running and opened thanks to the deep link, then first the initialStep is processed to go to some home screen, and then the deep link makes the AppStep.view(id:) to be processed, so you have like 2 navigations ? first the initial step and then the .view(id:) step ?

**Comment by MatrixSenpai** [comment]
Your first point is correct. However, when the app is _not_ open, AppStep.view(id: ) is never called

**Comment by twittemb** [comment]
Is it ok to share you whole project so I can take a look ?

**Comment by MatrixSenpai** [comment]
Please see this repo: https://github.com/LiveTL/ios

**Comment by twittemb** [comment]
Thanks a bunch. Is there an easy way to trigger the scheme ?

**Comment by MatrixSenpai** [comment]
Ensure the app is not running in the background. Head to YouTube in either Safari or the YT app and share a video. In the action sheet, "Translate in LiveTL" should appear (if it does not, try restarting or run the extension scheme attached to safari or yt). The app will go to .home instead of .view(id: )

**Comment by twittemb** [comment]
Ok, will do. Thanks for providing all those details. That will help to explore the issue.

**Comment by twittemb** [comment]
Hey @MatrixSenpai 

After a few tests, I noticed that the `func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>)` is not called when you share a video from Youtube and the application is not running.

You can reproduce that by playing a sound or an haptic feedback in this functions.

I'm not sure this is related to RxFlow. Have you tried an RxFlow free version of your app ?

**Comment by MatrixSenpai** [comment]
Interesting, I have not. That doesn't make sense though, because it opens the app…I'll do some further testing and report back

**Comment by MatrixSenpai** [comment]
So, interesting to note that `UIApplication.application(app:, open url:, options:)` does actually fire, while `SceneDelegate.scene(scene:, openURLContexts: )` does not. Appears to be an inconsistency within Apple's platform, so I'm gonna go ahead and close this issue and try to find a workaround
