### ISSUE TITLE
How to handle opening multiple flows upon clicking a deeplink

### ISSUE THREAD

**Issue by sree127** [RxSwiftCommunity/RxFlow#168]
### Scenario & use case
1. Deeplink with a scheme: `app://settings/account` is clicked and a step is forwarded to all the flows by the coordinator
2. Deeplink.step is consumed by `MainFlow`
3. `MainFlow` then opens `SettingsFlow`
4. `SettingsFlow` then opens `AccountFlow`

#### From the `MainFlow`
```
func navigateToSettings(withNextStep: Step? = nil) -> FlowContributors {
    let settingsFlow = SettingsFlow()
    
    Flows.use(settingsFlow, when: .ready) { [weak rootViewController] root in
      rootViewController?.present(root, animated: true, completion: {
        // The only way currently to process next step in case of deeplink is as follows
        // This needs to be refactored once we have a better solution on how to handle multiple flows
        if let nextStep = withNextStep {
          settingsFlow.stepper.steps.accept(nextStep)
        }
      })
    }

    return .one(flowContributor: .contribute(withNextPresentable: settingsFlow, withNextStepper: settingsFlow.stepper))
  }
```

#### From the `SettingsFlow`

```
 func navigateToAccounts() -> FlowContributors {
    let stepper = AccountsStepper()
    let accountsFlow = AccountsFlow(t)
    
    Flows.use(accountsFlow, when: .ready) { [weak navigationController] root in
      navigationController?.presentAnimated(viewController: root)
    }
    
    return .one(flowContributor: .contribute(withNextPresentable: accountsFlow, withNextStepper: stepper))
}
```

As you can see, the current way of opening another flow had to be done inside the `completion` block of `rootViewController.present` & I think that's not the cleanest approach.

I would be very interested to know what other alternatives can I use to achieve the same behaviour? Thanks in advance 😊 @twittemb

**Comment by mgray88** [comment]
@sree127 Could you use a `CompositeStepper`? Is this still an issue with the current version of the library?
