### ISSUE TITLE
Reentrancy anomaly on .forwardToCurrentFlow

### ISSUE THREAD

**Issue by erginbilgin** [RxSwiftCommunity/RxFlow#175]
Using .forwardToCurrentFlow(withStep:) causes a reentrancy anomaly. It is observable on demo project as well, right after SettingsFlow:93 (Run demo app and tap on settings button).

**Comment by erginbilgin** [comment]
@twittemb Are you still maintaining the project?

**Comment by twittemb** [comment]
@erginbilgin Hi, thanks for reaching. I'm still maintaining the project, I was on vacation with no computer ☺️.
I will check this issue ASAP.

**Comment by twittemb** [comment]
Hey @erginbilgin, could you give it another try on the branch feature/bump-deps (please perform a Carthage bootstrap because the deps have been bumped)

thanks.

**Comment by erginbilgin** [comment]
@twittemb I will do at the first opportunity I find. 👍 Did you have a chance to check the other issue which I opened? https://github.com/RxSwiftCommunity/RxFlow/issues/176

**Comment by twittemb** [comment]
@erginbilgin can you try the new 2.12.4 release please ?

**Comment by erginbilgin** [comment]
It is not available yet in CocoaPods as I see. Will you push there soon?

**Comment by twittemb** [comment]
I've just released it :-)

**Comment by erginbilgin** [comment]
@twittemb Sorry for delay. Just tested it and warnings are gone. Seems like https://github.com/RxSwiftCommunity/RxFlow/issues/176 is solved too. Amazing. Thanks!

**Comment by twittemb** [comment]
Hey @erginbilgin 

Happy to hear that.

Feel free to close the issues if you think they are resolved.

Bye.
