### ISSUE TITLE
RxFlowDemo nested NavigationControllers

### ISSUE THREAD

**Issue by beretis** [RxSwiftCommunity/RxFlow#18]
Hi, first of all thank you for your afford and time creating this interesting library. After playing around  in RxFlowDemo I couldn't find a way how to "switch flows" without pushing them to the "MainFlow root". 

I mean, in your app you have this structure: 
UINavigationController (MainFlow)
--UIViewController(apiKey)
--UITabBarController (apiKeyIsComplete)
----UINavigationController(WishlistWarp)
----UINavigationController(WatchedFlow)

What I dont like is, that you have nested UINavigationControllers and you have UITabBarController inside UINavigationController and then you have UINavigationController for every tab. I don't think this is best practice (ScrollViewInsets are weird that way and acording to documentation you UITabBar is meant to be root). 

I would rather create "APIFlow" with root (UINavigationContorller) and then I would have "DashboardFlow" with root (UITabBarController) and when "APIFlow" is finished I would like my UITabBarController to be as a root in my hierarchy. So i would like to somehow swap UIWindow's rootViewController from the flow's perspective. 

Im not sure If I described my point well enough. If you will agree, I can help afterwards.

**Comment by twittemb** [comment]
Hi @beretis 

Thanks for your feedback. It makes sense. Indeed, it could be interesting to be able to replace a Flow by another one.

I don't know it it is a good practice to replace the rootViewController of the UIWindow once it has been set a first time ? Do you have some feedback on this ?

I propose you 2 steps:
1 - Can you update to demo app to use the View Controllers hierarchy you suggest (UITabbarController at the root level for instance)
2 - I will work on a mechanism to allow to replace a Flow by another one.

What do you think about that ?

**Comment by beretis** [comment]
Hi @twittemb, great to hear back from you. 
I created [https://github.com/RxSwiftCommunity/RxFlow/pull/22](PR22) where I implemented swapping root flows and edited DemoApp to have hierarchy according to our discussion. 
It's just an idea, feel free to change things.

**Comment by twittemb** [comment]
Hi @beretis 

Thanks for your PR. I close this issue since our conversation will take place in the PR.

Thx.
