### ISSUE TITLE
Seeking a new maintainer

### ISSUE THREAD

**Issue by twittemb** [RxSwiftCommunity/RxFlow#188]
Hi everyone,

As the creator and maintainer of this project for 5 years, I have to step back from it due to a lack of free time.
I can’t find the time for responding or reviewing PRs and it’s harmful to the project. 

If anyone wants to jump in I’d be glad to grant him the maintainer rights.

Let me know if you’re interested.

Thanks.

**Comment by mgray88** [comment]
Hey @twittemb, I'd love to help out!

**Comment by twittemb** [comment]
Hi

Great. Let me get back to you in how to proceed.

**Comment by twittemb** [comment]
I have added you as a maintainer. What would you need more ?

**Comment by twittemb** [comment]
The first thing to do would be to go through all the PRs and decide whether or not they are still valid.

**Comment by mgray88** [comment]
@twittemb it looks like I don't have enough permissions to move forward. The CI workflow is not able to run as it is too old. I created a PR to update it, but I can't merge without a review. I'm not able to modify the requirements in the settings for PRs to be able to get around this.

**Comment by twittemb** [comment]
Hi. You should be good to go now (you are admin).
