### ISSUE TITLE
Initiating a step from a completion inside of a sink for Future Published (Combine)

### ISSUE THREAD

**Issue by maxgarmar** [RxSwiftCommunity/RxFlow#193]
Hi Guys,

I am working in a new applications trying your library and there is something really weird. 
I am using combine to make async calls to rest api (specifically Future Publisher). 
When I complete a call with and return the value it goes to the completion code of the sink, example like the following 

```swift
repositoryManager.fetchAuthSession()
                    .receive(on: DispatchQueue.main)
                    .sink( receiveCompletion: { [self] completion in
                    switch completion {
                    case .finished:
                        break
                    case .failure:
                        logger.w("Error fetchAuthSession expected because User SignedOut or the app just started")
                        // show onboarding or login
                        if userDataManager.getOnBoardingShownUserDefaults() ?? false {
                            logger.i("Redirecting -> login")
                            navigateToLogin()
                        } else {
                            logger.i("Redirecting -> Presentation Slide")
                            navigateToPresentationSlide()
                        }
                    }
                }, receiveValue: { [self]  in
                    logger.i("FetchAuthSession Success! Token stored")
                    // go to home or whatever
                }).store(in: &subscriptions)
``` 
when I go to the sink I need to react and do some redirection to a new Screen 
as you can see I am using the receive(on: DispatchQueue.main) so the completion code runs on the main thread, what is suppose to be the right for your Step to run like the following:

```swift
 func navigateToLogin() {
            self.steps.accept(AppStep.loginIsRequired)
    }
``` 

but interesting enough, if I do the code like above, the flow does not react to the step and the navigation does not work. 
Now if I do this:

```swift
 func navigateToLogin() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) { [unowned self] in
            self.steps.accept(AppStep.loginIsRequired)
        }
    }
``` 

Then the flow is triggered perfectly and it navigates to the next screen without changing a single line more in the code.

That tells like ... the code does not run in the main thread? but actually it does because I made this

```swift 
guard Thread.isMainThread else {
        fatalError("Code is not executing on the main thread")
    }
    self.steps.accept(navigationStep)
``` 

to make sure I was on the main thread, so it was but still RxFlow does not react. 

Any suggestion? am I doing something wrong or unexpected?

Thanks and appreciate your work for this library.

Cheers

Maximo

**Comment by mgray88** [comment]
My understanding of Combine is limited, other than its similarity to RxSwift in functionality. The red flag here in my opinion is the `.now() + 1`. That sounds to me like maybe RxFlow isn't ready to accept steps at the time you attempt to send them. Have you looked at #134? I myself faced a similar issue a while back; I ended up just working around it.

Can you create a small sample project that recreates the issue?

**Comment by maxgarmar** [comment]
Hey @mgray88 

Thanks for coming back so quick. 

Yes I checked that issue but not sure if it was related  and the workaround is not clear. 
Can you please share with me the workaround you did in the meantime I can prepare some example? I’m bit busy lately. 
The workaround I did only works when I make async.after + delay. If I don’t make a delay, sometimes does work and sometimes doesn’t. 

Thanks

**Comment by mgray88** [comment]
It sounds quite similar to the other issue, especially when you mention the sometimes works, sometimes doesn't when there is no delay. Our workaround to the original issue in #134 was to use main.async which then caused the "sometimes works" problem.

@ssaluk's workaround posted in [this comment](https://github.com/RxSwiftCommunity/RxFlow/issues/134#issuecomment-715227343) was to move logic to `viewDidAppear` since it seemed the issue surrounded `rxVisible`
