### ISSUE TITLE
Passing data throughout the Flow.

### ISSUE THREAD

**Issue by sirvon** [RxSwiftCommunity/RxFlow#23]
In this flow, in particular the func navigate(to:)
I'm passing data like, 3 times...

Is there anyway to avoid passing data so many times? like here:

```swift
func navigate(to step:Step) -> NextFlowItems {
        guard let step = step as? AppStep else { return NextFlowItems.stepNotHandled }
        
        switch step {
        case .destinationsNearMe(let lat, let long):
            return navigateToDestinationsNearMeList(with: lat, with: long)
        default:
            return NextFlowItems.stepNotHandled
        }
    }
    
    private func navigationToDashboardScreen() -> NextFlowItems {
        
    }
    
    private func navigateToDestinationsNearMeList(with lat: Double, with long: Double) -> NextFlowItems {
       
```

This same data is being passed three times,

```swift
        case .destinationsNearMe(let lat, let long):
            return navigateToDestinationsNearMeList(with: lat, with: long)
func navigateToDestinationsNearMeList(with lat: Double, with long: Double)
```
can you recommend or show an example of an RX way or a more efficient way to pass the data,
from the VC to the VM then to the Services/Data Providers/Networking, that need some
current user/device state info, to kick off processing.

**Comment by twittemb** [comment]
Hi @sirvon. There are 2 questions here, I will do my best to answer clearly:
**1 - Passing data**
First thing first, to ease this process you could wrap your values in a data structure (such as a Struct) to lower the amount of parameters. In your case you could pass a "Coordinate" Struct that holds your 2 values.
Then I think it is a good thing to be the more stateless as possible. It means that passing arguments between your layers is not a bad thing. The only workaround would be to have some Singleton that holds you current state, but Singleton is rarely a good practice. It could be done in a low level service that would be injected whenever you need to access this state (in your VM for instance).

**2 - Rx way of passing data**
The big advantage of using a MVVM combined to RxSwift is the possibility to use View binding. You can even do a 2 ways binding between your View and your ViewModel. It means that every changes that happen in one of these layers will be propagated to the other. RxCocoa provides many extentions to UIViews that allow this binding. Let's say you have a UITextField in your VC, and a VM that have a property of type Variable<String>. In the viewDidLoad function you can bind these two items:
```swift
self.myTextField.rx.text.orEmpty.bind(to: viewModel.myVariable).disposed(by: self.disposeBag)
viewModel.myVariable.asObservable().bind(to: self.myTextField.rx.text).disposed(by: self.disposeBag)
```
You could also bind a Variable stored in a Service to you ViewModel (this code should be inside the VM, consider that user.name is a Variable<String>):
```swift
myService.user.name.bind(to: viewModel.myVariable).disposed(by: self.disposeBag)
```

If you are not familiar with Rx programming and View binding, you should take a look at the Realm Academy: https://academy.realm.io/posts/learning-path-rxswift-from-start-to-finish/

I hope this helps.

**Comment by sirvon** [comment]
very excited right now! stay tuned @twittemb

**Comment by twittemb** [comment]
Hi @sirvon 

Sorry for the delay. To learn more about RxSwift, you should definitely buy the book made by the Raywenderlich team: https://store.raywenderlich.com/products/rxswift

It is a little bit expensive but it worth it.

To make this Rx binding code more "elegant", some have tried to implement custom operators to be able to write:
myTextField ~> viewModel.myVariable

"~>" would mean "bind to"

I'm sure you will find a lot of ressources on that, or perhaps implement your own custom operator.

If your agree I close this issue as I think the initial question has been answered.

Thanks.
