### ISSUE TITLE
Temporary Flows which root which is neither presented nor pushed - how to dismiss?

### ISSUE THREAD

**Issue by Sajjon** [RxSwiftCommunity/RxFlow#24]
I want to show several **temporary** flows before I will show the `MainFlow` (user signed in and show the main screen in the app).

The `AppDelegate`'s `Coordinator` coordinates to the `AppFlow` in `application:didFinishLaunchingWithOptions`.

The `AppFlow` will then navigate to several temporary flows before `MainFlow`, where each Flow has several screens (steps)

Lets say that we have these flow chart:
`AppStart> AppFlow --set-root--> FirstRunFlow  --set-root-->  SignInFlow  --set-root-->  MainFlow` 

I do not want the user to be able to navigate back from `SignInFlow` to `FirstRunFlow`. What makes sense is to completely replace the NavigationStack (the `UINavigationController` and its `UIViewController`s) of `SignInFlow` with a new `UINavigationController` when `SignInFlow` is done (last step reached) .

So for the temporary flows I guess I want to replace the `window` in `AppDelegate` with each temporary flows' `UINavigationController`.

I have created an example app but it is not working fully because I have not really been able to dismiss these temporary flows. Their `deinit` does not get called.

In the README it says

> In order to improve RxFlow consistency, it seemed obvious that a Flow that presents a UIViewController also **HAS** to dismiss it. In previous versions, a child Flow was dismissed by itself and not by the Flow that presented it. In the Demo Application you will find an example with the WishlistFlow dismissing the SettingsFlow for the **settingsDone** Step.

This sounds very relevant to what I want to do. I WANT to dismiss a Flow manually I guess? Because right now the framework seems to be working fine when `Presentable`s are presented or pushed.

How can I handle the scenario where I have several temporary `Flow`s I want to go through but disabling the possibility of navigating back and ultimately land on a `MainFlow` where the user spends most of her time (logged in and consuming content).

My example app is rather ambitious, please have a look: https://github.com/Sajjon/RxFlowExample

What to do? :)

**Comment by Sajjon** [comment]
@twittemb do you understand my question? :)

**Comment by twittemb** [comment]
Hi @Sajjon 

Sorry for the delay. Yes it makes sense. I'm currently thinking of a new feature that could fit your needs: A Flow could replace its parent Flow. But I'm still thinking how to do it the right way.

If you want to dismiss a Flow, you just have to dismiss its root ViewController (see the WishlistFlow in the demo app)

```swift
        case .settingsDone:
            self.rootViewController.presentedViewController?.dismiss(animated: true)
            return NextFlowItems.none
```

This code makes the WishlistFlow dismiss the SettingsFlow.

Your MainFlow could orchestrate the dismissal of old flows and the appearance of new ones, in your switch statement:

```swift
case newStep:
...
// dismiss the current Flow
self.rootViewController.presentedViewController?.dismiss(animated: true)
// launch a new Flow
let settingsFlow = SettingsFlow()
Flows.whenReady(flow1: settingsFlow, block: { [unowned self] (root: UINavigationController) in
            self.rootViewController.present(root, animated: true)
        })
return NextFlowItems.one(flowItem: NextFlowItem(nextPresentable: settingsFlow, nextStepper: OneStepper(withSingleStep: otherStep)))
```

Is it something that could do the job for you right now ?

**Comment by twittemb** [comment]
Hi @Sajjon 

Take a look a the demo app on develop. There is a AppFlow in which I replace the rootViewController of the UIWindow. That should help you.

Instead of displaying the SettingsScreen, you can instantiate a new Flow and display its root (use the Flows.whenReady function for that)

I hope this helps.

**Comment by Sajjon** [comment]
@twittemb Have you tried to implement several temporary Flows yourself? If you would have a look at https://github.com/Sajjon/RxFlowExample you will notice that this is not really straightforward now.

### The example project works but I get a nasty kind of warning 3 times

> ⚠️ Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/sajjon/Developer/Swift/iOS/Experimenting/TestingFlow/Pods/RxSwift/RxSwift/Rx.swift:97 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueing sequence events in some other way.
⚠️ Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/sajjon/Developer/Swift/iOS/Experimenting/TestingFlow/Pods/RxSwift/RxSwift/Rx.swift:97 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueing sequence events in some other way.
⚠️ Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/sajjon/Developer/Swift/iOS/Experimenting/TestingFlow/Pods/RxSwift/RxSwift/Rx.swift:97 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueing sequence events in some other way.

Take a look at my Steps to understand the flows, I have grouped them by indirect enum cases, where each nested enum conforms to `Step` and contains the case `start` and the case `done`:
```swift

enum AppStep: Step {
    
    case start // Never Ending Story
    
    indirect case first(First)
    static var firstStart: AppStep { return .first(.start) }
    enum First: Step {
        case start, done
        case applePay, applePayDone
        case permissions, permissionsDone
    }
    
    indirect case version(Version)
    static var versionStart: AppStep { return .version(.start) }
    enum Version: Step {
        case start, done
        case forceUpdate, forceUpdateBlock
        case onboarding, onboardingDone
    }
    
    indirect case auth(Auth)
    static var authStart: AppStep { return .auth(.start) }
    enum Auth: Step {
        case start, done
        case signInOrSignUp
        case signIn, signInDone
        case signUp, signUpDone
    }

    indirect case main(Main)
    static var mainStart: AppStep { return .main(.start) }
    enum Main: Step {
        case start // Never Ending Story
        indirect case tab(Tab)
        enum Tab: Step {
            case myStays, book, myPage, more
        }
    }
}
```

Steps:
AppStep.start -> startFirstFlow 
🎁 `Flows.whenReady(flow1: firstRunFlow) { [weak self] in self?.navigationController.present($0, animated: false, completion: nil) }`
=== FirstFlow ===
-> First.start -> First.applePay ->   
💣 replace `navigationController.rootViewController` with `ApplePaySplashViewController`  
⬇️ user presses `next` button -> First.applePayDone -> First.permissions  
💣replace `navigationController.rootViewController` with `PermissionsViewController`  
⬇️ user presses `next` button -> First.permissionsDone  
-> First.done ->  
AppFlow -> dismiss FirstFlow -> AppStep.startVersionFlow  
==== VersionFlow  ====  
🎁 `Flows.whenReady(flow1: versionFlow) { [weak self] in self?.navigationController.present($0, animated: false, completion: nil) }`  
Version.start -> Version.forceUpdate.....  

#### However, when I dismiss the `FirstRunFlow` I get this warning **three times directly after another**:

> ⚠️ Reentrancy anomaly was detected.
  > Debugging: To debug this issue you can set a breakpoint in /Users/sajjon/Developer/Swift/iOS/Experimenting/TestingFlow/Pods/RxSwift/RxSwift/Rx.swift:97 and observe the call stack.
  > Problem: This behavior is breaking the observable sequence grammar. `next (error | completed)?`
    This behavior breaks the grammar because there is overlapping between sequence events.
    Observable sequence is trying to send an event before sending of previous event has finished.
  > Interpretation: This could mean that there is some kind of unexpected cyclic dependency in your code,
    or that the system is not behaving in the expected way.
  > Remedy: If this is the expected behavior this message can be suppressed by adding `.observeOn(MainScheduler.asyncInstance)`
    or by enqueing sequence events in some other way.


# Dismissing temporary flow
I wanted each screen (ViewController) to be self contained. Which is one of the main idea from Khanlou in the Coordinator pattern. So take a look at the last screen in the `FirstRunFlow` called `PermissionsViewController` I let its viewModel `PermissionsViewModel` be the `Stepper` - being responsible for calling 
```swift
self.step(to: .first(.permissionsDone))
```
 Which is my syntactical sugar for: `self.step.accent(AppStep.first(.permissionDone))`

I do not call `step(to: .first(.done))` instead I use `.first(.permissionDone)` which is the *Permissions screen* (`PermissionsViewController`)s way of saying to `FirstRunFlow` that *"Now I am done"*. 

This makes the *Permissions screen* (`PermissionsViewController`) self contained, in the way that it does not know **and should not know** that it is the last step of the Flow. Instead I let `FirstRunFlow` decide what to do when it received the event `.first(.permissionDone)`, so it is handled in the Flow function `navigate:to`:
```swift
...
case .first(.permissionsDone):
            self.step(to: .first(.done))
            return .none
...
```

I tried changing that code to:
```swift
...
case .first(.permissionsDone):
            navigationController.presentedViewController?.dismiss(animated: true)
            self.step(to: .first(.done))
            return .none
...
```

But the `navigationController.presentedViewController?.dismiss(animated: true)` only made things worst, I still get the `⚠️ Reentrancy anomaly was detected.` warning, **not now 2 times instead of 3**, but the `PermissionsViewController` - probably the whole FirstRunFlow - does not get dismissed.

Changing the order of `navigationController.presentedViewController?.dismiss(animated: true)` and `self.step(to: .first(.done))` does not do anything.

So instead I use the *"solution"* that works, which is that the temporary flows, e.g. `FirstRunFlow` lets the "parent flow" `AppFlow` be responsible for dismissing it, as we saw in the code above, we call `self.step(to: .first(.done))` which is handled in the Flow function `navigate:to` in `AppFlow`:
```swift
        case .first(.done):
            navigationController.presentedViewController?.dismiss(animated: false)
            return navigate(to: AppStep.versionStart)```
```

## Issues
Apart from the terrible warnings  `⚠️ Reentrancy anomaly was detected.` (multiple), I do not really like the code.

## Requirements for Child Flows
1.  I want to show a navigationBar with title in the temporary flows
2. Each temporary flow is self contained and has its own navigationController and knows nothing about the other flows => It should not be possible to go back from `VersionFlow` back to `FirstRunFlow`
3. In most cases I do not want it to be able to go back between sceens within the same flow, e.g From `PermissionViewController` I do not want it to be possible to go back to `ApplePaySplashViewController`.



## Suggestions
### Child/Temporary Flows
Would it not be great if inside `AppFlow` I could write this code:

```swift
    func navigate(to step: Step) -> NextFlowItems {
        guard let step = step as? AppStep else { return .stepNotHandled }
        switch step {
        case .start: return navigate(to: AppStep.firstStart)
            
        case .first(.start): return .childFlow(FirstRunFlow(service: authService))
        case .first(.done): return navigate(to: AppStep.versionStart)
            
        case .version(.start): return .childFlow(VersionFlow(service: appConfigService))
        case .version(.done): return navigate(to: AppStep.authStart)
            
        case .auth(.start): return childFlow(AuthFlow(service: authService))
        case .auth(.done): return navigate(to: AppStep.mainStart)
            
        case .main(.start): return startMainFlow()
        default: return .stepNotHandled
        }
    }
```

Notice the `.childFlow(Flow)` enum type on `NextFlowItems`

And each Child flow could then just dismiss it self like this:
```swift
    func navigate(to step: Step) -> NextFlowItems {
...
        case .first(.permissionsDone): return .dismissed(AppStep.first(.done))
```

Or something like it.

### Simplify navigation stack handling?
It also feels a bit strange to have to return some abstract `NextFlowItems` *AND* also manually have to handle the navigation stack. In your simple example app you you have this code, inside `WishlistFlow`:

```swift
   private func navigateToMovieDetailScreen (with movieId: Int) -> NextFlowItems {
        let viewModel = MovieDetailViewModel(withService: self.service, andMovieId: movieId)
        let viewController = MovieDetailViewController.instantiate(with: viewModel)
        viewController.title = viewModel.title
        self.rootViewController.pushViewController(viewController, animated: true)
        return NextFlowItems.one(flowItem: NextFlowItem(nextPresentable: viewController, nextStepper: viewModel))
    }
```
It is the two list lines of code that I feel is a bit strange 
```swift
      self.rootViewController.pushViewController(viewController, animated: true)
        return NextFlowItems.one(flowItem: NextFlowItem(nextPresentable: viewController, nextStepper: viewModel))
```

What does actually returning `NextFlowItems.one(flowItem: NextFlowItem(nextPresentable: viewController)...` **do?** Would it be possible to not having to both manually push the viewcontroller on the navigation controller AND returning that `NextFlowItems` thing? :) 

Even in your example app and also in mine, the `var root: UIViewController` property on our `Flows` are almost always a `UINavigationController`. Would it not be possible to use that? And not having to both manually handle navigation stack logic and returning the `NextFlowItems` thing?

**Comment by twittemb** [comment]
Hi @Sajjon 
Thanks for this great feedback. I will take the time to read it with the attention it deserves. For now I will focus on the reentrancy issue since it is an obvious bug. I think it is due to the PublishSubject in the FlowCoordinator because it emits values inside its subscription.

I will do the test with you demo repo. 

I think @dangthaison91 has the same issue of reentrancy, so it is a good thing to start with this issue.

I will get back to you soon.

**Comment by Sajjon** [comment]
@twittemb Awesome, and THANK YOU for a really promising project! I feel very excited about this.

Sorry for my wall of text, it was not so well structured... Please let me know if you have any questions about writing about :P but I think maybe just looking at the project which is not too big, will make things more clear :)

**Comment by twittemb** [comment]
@Sajjon just to let you know I've not given up on this subject ... I'm just very busy right now but I have begun to work on a dedicated branch to test a swap feature between 2 flows.

Stay tuned.

**Comment by Sajjon** [comment]
@twittemb Great, looking forward to it!

I am a heavy user of `Swinject` and especially [SwinjectAutoregistration](https://github.com/Swinject/SwinjectAutoregistration) which plays nicely with RxFlow. I can then achieve this syntax in my `Flow` method `func navigate(to step: Step) -> NextFlowItems `:

```swift
 import RxFlow
import Swinject
import SwinjectAutoregistration

final class AuthFlow {
    
    private let container: Container
    
    init(container parent: Container) {
        container = makeContainer(parent: parent)
        self.step(to: .authStart)
    }
}

extension AuthFlow: Flow {
    var root: UIViewController { return container ~> UINavigationController.self }
    
    func navigate(to step: Step) -> NextFlowItems {
        guard let step = step as? AppStep else { return .stepNotHandled }
        switch step {
        case .auth(.start): return navigate(to: AppStep.auth(.signInOrSignUp))
        case .auth(.signInOrSignUp): return navigateTo(screen: Authenticate.self, in: container, presentation: .root)
        case .auth(.signIn): return navigateTo(screen: SignIn.self, in: container)
        case .auth(.signUp): return navigateTo(screen: SignUp.self, in: container)
        case .auth(.signInDone), .auth(.signUpDone): self.step(to: .auth(.done)); return .none
        default: return .stepNotHandled
        }
    }
}

extension AuthFlow: Stepper {}

private func makeContainer(parent container: Container) -> Container {
    return Container(parent: container) { c in
        c.register(UINavigationController.self) { _ in UINavigationController() }.inObjectScope(.container)
        
        c.autoregister(AuthLayout.self, initializer: AuthView.init).inObjectScope(.container)
        c.autoregister(AuthViewModel.self, initializer: AuthViewModel.init).inObjectScope(.container)
        c.autoregister(Authenticate.self, initializer: Authenticate.init).inObjectScope(.container)
        
        c.autoregister(SignInLayout.self, initializer: SignInView.init).inObjectScope(.container)
        c.autoregister(SignInViewModel.self, initializer: SignInViewModel.init).inObjectScope(.container)
        c.autoregister(SignIn.self, initializer: SignIn.init).inObjectScope(.container)
        
        c.autoregister(SignUpLayout.self, initializer: SignUpView.init).inObjectScope(.container)
        c.autoregister(SignUpViewModel.self, initializer: SignUpViewModel.init).inObjectScope(.container)
        c.autoregister(SignUp.self, initializer: SignUp.init).inObjectScope(.container)
    }
}

```

With some Helpers:
```swift

func navigateTo<ScreenStepper>(screen screenType: ScreenStepper.Type, in container: Container, presentation: PresentationStyle = .push(animated: true)) -> NextFlowItems where ScreenStepper: Screen & Stepper {
    let screen = container ~> screenType
    let navigationController = container ~> UINavigationController.self
    
    return _navigateTo(screen: screen, navigationController: navigationController, presentation: presentation)
}

private func _navigateTo<ScreenStepper>(screen: ScreenStepper, navigationController: UINavigationController, presentation: PresentationStyle) -> NextFlowItems where ScreenStepper: Screen & Stepper {
    let viewController = screen.makeViewController()
    
    switch presentation {
    case .root: navigationController.viewControllers = [viewController]
    case .push(let animated): navigationController.pushViewController(viewController, animated: animated)
    case .present(let animated): navigationController.present(viewController, animated: animated)
    }
    
    let flowItem = NextFlowItem(nextPresentable: viewController, nextStepper: screen)
    return .one(flowItem: flowItem)
}
```

Where `Screen` is my "abstract" `UIViewController` which can create an "anonymous" instance of a `UIViewController`, some of the code to give you an idea:

```swift

public protocol Screen: ViewOwner, KeyboardFrameAdjuster {
    
    var bag: DisposeBag { get }
    
    func makeViewController() -> UIViewController
    
    var viewDidLoad: ViewControllerCallback { get }
    var viewWillAppear: ViewControllerCallback { get }
    var viewDidAppear: ViewControllerCallback { get }
    var viewWillDisappear: ViewControllerCallback { get }
    var viewDidDisappear: ViewControllerCallback { get }
    
    var title: String? { get }
    var hidesNavigationBar: Bool { get }
    var rightBarButtonItem: UIBarButtonItem? { get }
    var backgroundColor: UIColor { get }
}

public extension Screen {
    
    func makeViewController() -> UIViewController {
        let viewController = UIViewController()
        bindViewControllerLifeCycleMethods(to: viewController)
        viewController.abstract = self
        return viewController
    }
    
    func bindViewControllerLifeCycleMethods(to vc: UIViewController) {
        bag <~~ vc.rx.viewDidLoad.subscribe() { [weak self, weak vc] _ in self?._viewDidLoad(vc) }
        bag <~~ vc.rx.viewWillAppear.subscribe() { [weak self, weak vc] _ in self?._viewWillAppear(vc) }
        bag <~~ vc.rx.viewDidAppear.subscribe() { [weak self, weak vc] _ in self?._viewDidAppear(vc) }
        bag <~~ vc.rx.viewWillDisappear.subscribe() { [weak self, weak vc] _ in self?._viewWillDisappear(vc) }
        bag <~~ vc.rx.viewDidDisappear.subscribe() { [weak self, weak vc] _ in self?._viewDidDisappear(vc) }
    }
}
```

Resulting in super small clean abstract "Screens":

```swift

final class Authenticate {
    
    private let layout: AuthLayout
    private let viewModel: AuthViewModel
    let bag = DisposeBag()
    
    init(
        viewModel: AuthViewModel,
        layout: AuthLayout
        ) {
        self.viewModel = viewModel
        self.layout = layout
        setupBindings()
    }
}

extension Authenticate: Stepper {}

private extension Authenticate {
    
    func setupBindings() {
        bindInputs(to: viewModel.input, from: layout, disposedBy: bag) {[
            \.signUp <?~ \.signUp,
            \.signIn <?~ \.signIn
        ]}
        
        bag <~~ viewModel.output.signUp.subscribeNext(weak: self, Authenticate.signUp)
        bag <~~ viewModel.output.signIn.subscribeNext(weak: self, Authenticate.signIn)
    }
    
    func signUp() { step(to: .auth(.signUp)) }
    func signIn() { step(to: .auth(.signIn)) }
}

extension Authenticate: Screen {
    var title: String? { return "HC: Welcome" }
    var rootView: UIView { return layout.rootView }
    var hidesNavigationBar: Bool { return true }
    var viewDidAppear: ViewControllerCallback { return { [weak self] _ in self?.layout.startStormVideo() } }
}
```

Neat ha?

**Comment by twittemb** [comment]
@Sajjon @dangthaison91 

Hi guys, I did have a look (very quick) to your repos. I think the reentrancy issue comes from the fact the you trigger new Steps directly inside some Flows.

If you take a look a the Coordinator code, you will see that the "navigate(to:)" func is called pretty early in the Rx subscription chain and when you fire a new Step the current subscription has not reached the end of the chain. 

IMHO a Flow should not be a Stepper. Steppers should be produced be the Flow through NextFlowItems.

I agree with you, my code should be more flexible or at least it should not allow a Flow to trigger steps. And I will think about a way to do so, but for now can you change your code so a Flow doesn't fire Steps. If this works we will know for sure what to do to prevent that.

Thanks for your help.

**Comment by dangthaison91** [comment]
You are right @twittemb . I will try to remove Step adoption for Flow.
Other way, while using RxFlow, I see your implementation is flexible but I want a better document or one way to help users avoid using it in wrong way.

**Comment by Sajjon** [comment]
@twittemb Thank you for commitment :) I really appreciate all help!

I must be stupid... but I still do not understand how I would implement what I want without letting the `Flow` also be a `Stepper`s.

I will make an attempt to be as concise as possible, by using example code so that it is clear what I need help with, in a nutshell, this is what my `AppDelegate` looks like:

```swift
import RxFlow

@UIApplicationMain
class AppDelegate: UIResponder {
    
    var window: UIWindow?
    private let coordinator = Coordinator()
    private lazy var appFlow: AppFlow = AppFlow(container: container)
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)
        window.makeKeyAndVisible()
        self.window = window
        Flows.whenReady(flow1: appFlow) { [unowned window] in window.rootViewController = $0 }
        coordinator.coordinate(flow: appFlow, withStepper: appFlow)
        return true
    }
}
```

So the *root* `Flow` is called `AppFlow` and it coordinates the whole app. Maybe using your suggestion this should only be a `Stepper`? But then it can't start flows... which I need. In a nutshell, this is what the `AppFlow` looks like:

```swift
final class AppFlow: Flow, Stepper {

    private let navigationController = UINavigationController()
    var root: UIViewController { return navigationController }
    
    
    init(container parent: Container) {
        step.accept(AppStep.start)
    }

    
    var initialStep: Step {
        guard hasRunAppBefore else { return AppStep.firstStart }
        let step: AppStep = isLoggedIn ? .mainStart : .authStart
        return step
    }
    
    func navigate(to step: Step) -> NextFlowItems {
        guard let step = step as? AppStep else { return .stepNotHandled }
        switch step {
        case .start: return navigate(to: initialStep)
            
        case .first(.start): return startFirstRunFlow()
        case .first(.done):
            navigationController.presentedViewController?.dismiss(animated: false)
            return navigate(to: AppStep.versionStart)
            
        case .version(.start): return startVersionFlow()
        case .version(.done):
            navigationController.presentedViewController?.dismiss(animated: false)
            return navigate(to: AppStep.authStart)
            
        case .auth(.start): return startAuthFlow()
        case .auth(.done):
            navigationController.presentedViewController?.dismiss(animated: false)
            return navigate(to: AppStep.mainStart)
            
        case .main(.start): return startMainFlow()
        default: return .stepNotHandled
        }
    }
}
```

**I still don't understand the following: What _Type_ will replace (temporary) `FirstRunFlow` with (temporary) `AuthFlow`?** Also actually I want this to be conditional, like this:

```swift
    var initialStep: Step {
        guard hasRunAppBefore else { return AppStep.firstStart } // This presents the `FirstRunFlow`
        let step: AppStep = isLoggedIn ? .mainStart : .authStart
        return step
    }
```
I am sorry if I missed clear instructions from you regarding this question, then maybe you can repeat your answer? :) 

in the computed property `initialStep: Step` above, being used by `AppFlow` I conditionally either start this chain of flows: 
### Scenario 1: Not logged in, first time running app:
_Temporary flows_: `[FirstRunFlow, NewVersionFlow, AuthFlow]` _finally_ `=> MainFlow`

### Scenario 2: Not logged in, _not_ first time running app, but first time running this version:
_Temporary flows_: `[NewVersionFlow, AuthFlow, MainFlow]` _finally_ `=> MainFlow`

### Scenario 3 Not logged in, _not_ first time running app, _not_ first time running this version:
_Temporary flows_: `[AuthFlow]` _finally_ `=> MainFlow`

### Scenario 4 Logged in:
_Directly_ `MainFlow`

As you can see we have three different kinds of arrays of Temporary Flows. So I cannot just use `CompositeStepper([FirstRunFlow(), NewVersionFlow(), AuthFlow()])`, right?

And each temporary Flow needs to tell some... Flow that it is done, in this case, `AppFlow`.

So I think my question really boils down to this:
## What mechanism presents/starts `NewVersionFlow` when `FirstRunFlow` is done?
This question is relevant for scenario 1-3 described above. Because I cant just dismiss `FirstRunFlow` and magically have `NewVersionFlow` being presented... Some _Type_ have to handle that, and now that is handled in `AppFlow` because it conforms to `Flow` it can _listen_ to Steps and navigate to the next Flow.  You suggested I don't let `FirstRunFlow` conform to `Stepper`? But how will `AppFlow` be notified that it should show `NewVersionFlow`?

I would really really love to hear your solution to this! :D

**Comment by Sajjon** [comment]
@dangthaison91 @grafele @TobiasRe If you have the time, please read my question above ⬆️ how did you solve this scenario? :)

**Comment by twittemb** [comment]
@dangthaison91, I agree with you about te document that could prevent the developper to mis use RxFlow. Do you think you can amend the Readme in that way and make a PR ?

**Comment by dangthaison91** [comment]
@twittemb I tried to remove Step in `HomeFlow` implementation but still got Reentrancy warning. Please take a look at https://github.com/dangthaison91/RxFlowDemo.

I think we should try to implement FlowCoordinator again from scratch and try another approach.

@Sajjon I think basically I'm trying to do like you but also having some issues.

**Comment by Sajjon** [comment]
@twittemb I am closing this issues since RxFlow supports this scenario in version 1.3 using `end(withStepForParentFlow:`
