### ISSUE TITLE
Global Stepper implementation

### ISSUE THREAD

**Issue by TobiasRe** [RxSwiftCommunity/RxFlow#25]
I really like the `RxFlow` approach for separating navigation with flows.
Which works really well with navigating step by step as the user uses the app gets complicated with deep linking (e.g.: Navigating to ViewController after receiving a push notification).

**How do I implement a global stepper for deep linking?**  
The `Stepper` should do the following:

1. Accept a specific `Step`
2. Select or create and attach the corresponding `Flow`
3. Add the `Step`to the flow

**Comment by twittemb** [comment]
Hi @TobiasRe 

Thanks for your feedback.

I think you could use the new "CompositeStepper" feature. In your AppDelegate you could something like that (adapt to your case of course)

```swift
let deepLinkStepper = DeepLinkStepper()
let mainStepper = CompositeStepper(steppers: [OneStepper(withSingleStep: DemoStep.apiKey), deepLinkStepper])
 coordinator.coordinate(flow: mainFlow, withStepper: mainStepper)
```

**DeepLinkStepper** should be a custom Stepper that you have to write (just implement the Stepper protocol).

You will trigger your instance of **deepLinkStepper** when a notification is received (DeepLinkStepper can have a function per notification type for instance). As it is associated to the MainFlow, Steps triggered by the DeepLinkStepper will be catched in that flow and you just have to implement the navigation in the **switch** statement of the **navigate(to:)** function.

Does it fit with your needs ?

**Comment by TobiasRe** [comment]
Thanks @twittemb 

Yes the `CompositeStepper` helps, if I including navigation to the corresponding sub flows in my `MainFlow`.
The issue that remains is how to handle deep linking on app start. Especially if the app needs some kind of bootstrapping/login before the app is ready to handle the deep link.

I guess the best to create an `Observable` where the deep link step is queued until the app is ready. 
```swift 
let deepLinkObservable = deepLinkSteps.sample(mainStepper.steps.filter{$0 == AppSteps.ready})
deepLinkObsersavable.subscribe(onNext: {step in 
    deepLinkStepper.accept(step)
}).disposed(by: disposeBag)
```
or similar.

**Comment by sirvon** [comment]
@TobiasRe 

You're saying, like If a push notification comes in 
and it requires login or some other Flow, before the user is taken to the screen/view, that the push notification pertains to, which might be in a different Flow from Login.

How to accept the user's action on that push notification, and then navigate to the Login/Bootstrap Flow, and then go to the Flow the push pertained to.....

@twittemb is it possible to have steps that EVERY FLOW created has access to?

**Comment by TobiasRe** [comment]
This feature is currently on hold for me.
There are serious memory management issues with RxFlow to fix first.

I can create a PR when the `Deeplink Stepper` implementation is done.
Let's close this for now.

**Comment by sirvon** [comment]
@TobiasRe please make an issue or talk about the memory issues
