### ISSUE TITLE
`dismissed` observable triggered without view being dismissed

### ISSUE THREAD

**Issue by grafele** [RxSwiftCommunity/RxFlow#26]
Hey,

I really like your framework and we tried using it in one of our apps. Right now we are facing a problem when showing a simple alert view and because of that I started investigating what was going on in the framework and I think I found a bug in the `dismissed` observable causing multiple other problems.

How to reproduce:
Show an alert in an UINavigationController
Dismissing the alert leads to an event being fired for the `dismissed ` observable of the UINavigationController.

This leads to multiple other issues, because the 'rxDismissed' observable will be fired therefore as well for the flow and our flow doesn't react to any event anymore even tho this view is still there.

**Comment by grafele** [comment]
I opened a pull request to resolve that issue: https://github.com/RxSwiftCommunity/RxFlow/pull/27

**Comment by twittemb** [comment]
Hi @grafele 
Thanks for your feedback. I've just merge your PR, great job.
Do you have a precise idea of why my original code was not working ? I don't understand why the "dismiss" method was called as it was only the Alert that was dismissed, not the root ViewController.

**Comment by grafele** [comment]
Hi @twittemb ! I think the AlertViewControllers buttons don't call the dismiss function on the AlertViewController but on it's presentingViewController. That leads to the exact same effect: The alert will be dismissed, but it triggered also the old 'dismissed' observable, because it listened on the dismiss method call on the view controller itself.

The documentation on apple side actually helps:
```
The presenting view controller is responsible for dismissing the view controller it presented. If you call this method on the presented view controller itself, UIKit asks the presenting view controller to handle the dismissal.
```

**Comment by twittemb** [comment]
Thanks for this explanation. It makes sense.

I close this issue as it has been resolved.

Thanks again, and feel free to contribute again ! help is always welcome.
