### ISSUE TITLE
Add willNavigate: Observable<Flow,Step> and didNavigate: Observable<Flow,Step> to Coordinator

### ISSUE THREAD

**Issue by Gruppio** [RxSwiftCommunity/RxFlow#29]
Hi, 
Currently the coordinator object has only 2 rx streams (willNavigate, didNavigate) that are specialized with 2 Strings that describes the Flow and the Step. 
```swift
var willNavigate: Observable<(String, String)>
var didNavigate: Observable<(String, String)>
```
These are very useful for "Analytics purposes".

My idea is to add 2 more streams, that are basically the same but instead to have 2 Strings as specialized Types, they will have a Flow and a Step
```swift
var willNavigate: Observable<(Flow, Step)>
var didNavigate: Observable<(Flow, Step)>
```
These streams are very powerful because allow the coordinator to act on the Flow or on the Step during the Navigation. For example the coordinator can then set a specific property by checking Protocol Conformance acting like as a "Dependency Resolver".

Moreover this extend the analytics capabilities of the current solution. So it's possible to have a custom logging convention per Flow or per Step.

If you need more detailed explanation don't hesitate to contact me 😃

**Comment by sirvon** [comment]
Hey, whats your use case for this. Can you talk about or show some pseudo code to describe how what you implement with this added feature? I would love to possibly add it in my projects.

**Comment by Gruppio** [comment]
Yes, suppose that some of your Flows are conform to this protocol 
```swift protocol ServiceProvider {
   var services: Services! { get set }
}```

And you have instantiated in the AppDelegate the instance of Service to use

So always in the AppDelegate you can use the "preNavigation" to set the Service instance to every Flow that is conform to ServiceProvider  

```swift
coordinator.rx.preNavigation.subscribe(onNext: { [weak self] flow, _ in
            guard var servicesProvider = flow as? ServicesProvider,
                let services = self?.services else { return }
                servicesProvider.services = services
        }).disposed(by: disposeBag)
```

**Comment by twittemb** [comment]
Hi @Gruppio @sirvon 

I am not sure I see your point. Since the preNavigation is trigger each time a navigation occurs, the dependency will be injected each time as well ?

**Comment by Gruppio** [comment]
Hi @twittemb @sirvon 
Yes with the code that I have posted, but this can be easily avoided with a nil check :-) .
I think that the point is to have the ability to inject dependencies from outside.
In this way each flow easily became also a container for the dependencies needed by his child ViewControllers or ViewModels. 
With this approach you can avoid global variables or ".shared" singletons, and you don't have to manually pass all the possible dependencies from an initializer to the next one.

Another advantage bring by "preNavigation" and "postNavigation" streams is that you can have custom analytics values.
I love the way that the coordinator can easily handle navigation analytics logging, but if you need to have specific Analytics names for each Flow and Step currently you have to manually map each Flow and step string to the desired ones.
Instead you can easily avoid the manual mapping using the 2 new streams.

```swift
protocol Trackable {
var customAnalyticsLabel: String { get }
}
```

```swift
coordinator.rx.postNavigation.subscribe(onNext: { flow, step in
          guard let flowTrackable = flow as? Trackable, 
          let stepTrackable = step as? Trackable else { return }
          print("\(flowTrackable.customAnalyticsLabel) did navigate to: \(stepTrackable.customAnalyticsLabel)" )
        }).disposed(by: disposeBag)
```

In this way customAnalyticsLabel can be any string that you want or even a computed one.

These are just 2 possible use cases, i believe that there are much more :-)

**Comment by Gruppio** [comment]
I've created the PR #31 Some days ago

**Comment by twittemb** [comment]
@Gruppio 

Hi. Sorry for the delay. I've been really busy lately. I think your proposal is a good one and will be part of the next release. My concern was about memory leak since Flow and Step will be given to a closure and I am not sure the developers won't be retaining them.

I think you should modify your PR to replace the actual will(did)Navigate(String, String) by will(did)Navigate(Flow, Step).

It is a breaking change but if it brings value to the developper its worth it.

Is that ok with you ?

**Comment by Gruppio** [comment]
Great! 
I will change it! no problem 👍 

Thank you :-)

**Comment by Gruppio** [comment]
PR #35

**Comment by twittemb** [comment]
@Gruppio your PR has been merged !
good job.
Thanks.
