### ISSUE TITLE
Type AppFlow does not conform to protocol Flow

### ISSUE THREAD

**Issue by snowtema** [RxSwiftCommunity/RxFlow#34]
I cloned your example project, deleted Carthage support and created my own Podfile and tried to compile, but I occured an errors like this:
`Type 'WatchedFlow' does not conform to protocol Flow` and etc `Flow`'s
![2018-02-20 16 26 24](https://user-images.githubusercontent.com/24715092/36426755-36bbc50a-165c-11e8-85fc-a95210636e5a.png)

When I created a new empty project, linked pods, created my own Flow class like **AppFlow**, I also occured this error.

My environment:
 - Xcode 9.2
 - Swift 4

My Podfile:

    use_frameworks!
    target 'RxFlowDemo' do
      pod 'RxSwift'
      pod 'RxCocoa'
      pod 'RxFlow'
      pod 'Reusable'
    end

What I'm doing wrong?

**Comment by twittemb** [comment]
Hi @snowtema 

Can you try to clone this repo: git@github.com:twittemb/RxFlowPodsDemo.git

and do a "pod update / pod install" ?

**Comment by 1397v** [comment]
I'm having the same issue using Carthage:
![image](https://user-images.githubusercontent.com/7044976/36468571-26d806de-16e4-11e8-8069-9d48b7efe4d7.png)

And when I use the help from Xcode it adds this:
![image](https://user-images.githubusercontent.com/7044976/36468597-3bd9b5c8-16e4-11e8-81fd-6f8fe7d87e1e.png)

**Comment by snowtema** [comment]
Hi @twittemb ! 
Thanks for your feedback!

Yes, your code compiles fine. But if I change the type of **var root: Presentable**, I have the same error. Why I can't use **Presentable** protocol?

**Comment by 1397v** [comment]
Update: I changed the AppFlow as follows:

```swift
class AppFlow: Flow {

    var root: UIViewController {
        return self.rootViewController
    }

    private var rootViewController: UIViewController
    private let service: MoviesService

    init(withRootViewController rootViewController: UIViewController, andService service: MoviesService) {
        self.rootViewController = rootViewController
        self.service = service
    }
```
And in the places the window was used inside `AppFlow`:
```swift
self.rootViewController = settingsViewController
```
And:
```swift
self.rootViewController = tabbarController
```

Then, in the `AppDelegate` I had to change:
```swift
guard let rootViewController = self.window?.rootViewController else { return false }

        coordinator.rx.didNavigate.subscribe(onNext: { (flow, step) in
            print ("did navigate to flow=\(flow) and step=\(step)")
        }).disposed(by: self.disposeBag)

        self.appFlow = AppFlow(withRootViewController: rootViewController, andService: self.movieService)
```


Finally, when everything compiled, I got this error:
![image](https://user-images.githubusercontent.com/7044976/36471595-473f4256-16ef-11e8-8bae-370121300d28.png)

**Comment by snowtema** [comment]
@1397v I haven't skill in Carthage, but I think your problem in wrong project settings for this framework, f.e. search path or other stuff.

**Comment by 1397v** [comment]
@snowtema the version I am using is the last one: 
![image](https://user-images.githubusercontent.com/7044976/36472595-91a98d1c-16f2-11e8-88c7-5ee4fe0ce075.png)

**Comment by twittemb** [comment]
@snowtema 

In the version 1.1.0 the Flow protocol declares a UIViewController as its root. The Presentable conformance is only on "develop" right now.

**Comment by snowtema** [comment]
@twittemb 

Ok, thanks! When do you want to release current **develop** version? Will this version with major changes?

**Comment by twittemb** [comment]
@snowtema 

I have no precise date for the next version. This will be a 1.2.0 with some important features such as Flow replacement.

**Comment by twittemb** [comment]
@1397v 

Can you try to clone this and give it a try: git@github.com:twittemb/RxFlowCarthageDemo.git

**Comment by 1397v** [comment]
@twittemb Yeah it works, but that demo only has 2 views and I intended to test the flow in a more "complex" architecture like the one in the demo because I intended to use this framework in a complex project.
For now I think I will build another navigation architecture and wait until RxFlow is stable. But thanks anyway.

**Comment by snowtema** [comment]
@twittemb Hello! I'm stuck again with Flow protocol. I need to implement **SplashViewController**, but when I declared `class SplashFlow: Flow { }` with `var root: UIWindow`, I have the same error. Can current release of **RxFlow** use **UIWindow**  in **root** for navigation flow?

**Comment by twittemb** [comment]
Hi @snowtema 
I have just release a version 1.2.0 on CocoaPods that handles that case.
Can you give it a try ?
thanks.

**Comment by snowtema** [comment]
@twittemb Thanks a lot! Your library is amazing! =)

**Comment by twittemb** [comment]
Thanks for your feedback.

Is it OK to close this issue ?

**Comment by snowtema** [comment]
@twittemb Yeah, version 1.2 working properly. The issue is not actual anymore.

**Comment by twittemb** [comment]
👍
