### ISSUE TITLE
Remove nested frameworks

### ISSUE THREAD

**Issue by TobiasRe** [RxSwiftCommunity/RxFlow#36]
The RxFlow framework should not contain nested frameworks!
At the latest during submitting to the AppStore, developers will prompted errors that RxFlow contains illegal nested frameworks.
To fix that disable the `Copy Carthage Frameworks` build phase for the framework.

![bildschirmfoto 2018-02-22 um 13 30 54](https://user-images.githubusercontent.com/2148814/36538723-ca798006-17d4-11e8-8f93-8bb9efd35ecd.png)

![bildschirmfoto 2018-02-22 um 13 42 18](https://user-images.githubusercontent.com/2148814/36539303-a3b8a508-17d6-11e8-85ea-348c549104f1.png)

**Comment by twittemb** [comment]
hi @TobiasRe 
thanks for this feedback. I have just push a fix en develop for that. Can you give it a try ?
thanks.

**Comment by twittemb** [comment]
Hey @TobiasRe 

Did you have time to submit your app again ?

**Comment by TobiasRe** [comment]
Yes I can confirm. This issue is resolved on the master branch.
