### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by benjohnde** [RxSwiftCommunity/RxFlow#38]
Are the docs hosted anywhere? Haven't found the place yet :)

Btw really nice library, love how it helps to reduce the boilerplate in our platform.

**Comment by twittemb** [comment]
Hi again @benjohnde 

The Readme is a good start :-)

There are also 3 blog posts here: https://twittemb.github.io (RxFlow Part1 / Part 2 / Part 3). This blog also hosts several articles of mine about conception patterns.

Does that help ?

**Comment by benjohnde** [comment]
Ah, right now I do not need any help, but spotted the docs directory and wondered if those are hosted anywhere :) I found them useful (so cloned the repo and opened the index).

**Comment by twittemb** [comment]
The docs directory is local to the projet (made with Jazzy). But you're right about hosting it somewhere. I will put it on my blog and add a link in the Readme.

👍

**Comment by twittemb** [comment]
Hi @benjohnde 

The doc is now available online: http://community.rxswift.org/RxFlow/

If you agree with that I will close this issue ?

**Comment by benjohnde** [comment]
Yeah for sure, thanks a lot!
