### ISSUE TITLE
Serious Memory Management Issues

### ISSUE THREAD

**Issue by sirvon** [RxSwiftCommunity/RxFlow#40]
A comment was left by @TobiasRe on this issue #25, about...

`There are serious memory management issues with RxFlow to fix first.`

Can anyone with production/ or app store release experience with this framework,
comment about any memory leaks they've discovered.

Thanks

**Comment by TobiasRe** [comment]
Hi @sirvon 
To explain the problem I'm referring to:

My ViewControllers are retained by RxFlow. Every transition to a new step causes an increase in memory use. Even the navigation to a detail ViewController, back to the list, open same detail ViewController causes this result.

My navigation hierarchy is like this:
`UINavigationController (MainFlow Root) -> UITabBarController (containing multiple flows) -> UITableViewController (Tab1Flow Root) -> UIViewController (Detail View)`

I know it's unusual to have a `UINavigationController` as a parent of a `UITabBarController`, yet this has to stay this way.

**Comment by TobiasRe** [comment]
So far I can tell that the `rxDismissed` Observable is not working as expected.

@twittemb Did you test this feature?

**Comment by twittemb** [comment]
Hi guys,

Can you try your apps with the branch feature/onboardingFlow.

Basically there are 3 things new here:
- the way FlowCoordinators are cleared is better (and Threadsafe)
- there is a new NextFlowItems type -> .end(withStepForParentFlow:Step). It allows to end a sub flow and tells its parent on which step to go on
- the demo app has been updated to show an example of root flow swapping ... the first time you launch the app there is an Onboarding flow that is replaced by the dashboard flow. After this first start, the onboarding flow will never happen again (unless you uninstall the app). The logic is done in the AppFlow Stepper.

Thanks for your feedback.

**Comment by twittemb** [comment]
@TobiasRe hi

Can you be more precise about the rxDismissed malfunction ? From What I see there is no such leak on the demo App. Recently the behavior of the rxDismissed Observable has been changed because there was an issue with Alert popups.

**Comment by Dimentar** [comment]
Hi guys.
From first implementation in my project I also had some memory issues, but the problems was not with **RxFlow**.
What I've noticed was: 
1. Never instantiate **ChildFlow** with `rootViewController` of **ParentFlow** from which you will present some `childViewController`, `rootViewController` being part of **ParentFlow** will not trigger `rxDismissed` during dismissing of `childViewController` -> **ChildFlow** will not be removed. Use **Flows.whenReady(...)** for present child, this gives you the possibility of different presentation mode from different places.
2. Also any cycle reference in `viewController` with `root` role -> will not remove **ChildFlow** (obviously).

**Comment by sirvon** [comment]
@dimentar Can you post some example code or an example repo?

**Comment by Dimentar** [comment]
Hi guys.
@sirvon [RxFlowMemory](https://github.com/Dimentar/RxFlowMemory), you will find 3 mode of flow allocation (with/without memory issues)

**Comment by twittemb** [comment]
Hi @Dimentar

Thanks a lot for your examples. I have on question: why do you have to pass the root viewController to the ChildFlow ?

**Comment by Dimentar** [comment]
Hi @twittemb.
On my first attempt at RxFlow implementation, in one use case, I've tried to pass `UINavigationController` (_root_ of **ParentFlow**) to **ChildFlow** from which I presented modally another VC (bad idea). However, I've noticed memory leaks, whats why I don't recommend to pass it to the **ChildFlow**. 

An important rule to follow is: Never pass _root_ of **ParentFlow** to **ChildFlow** because Flow deallocation depends on _root_ **rxDismissed** observable. Instantiate **Flow** _root_ inside, accessing it by **Flows.whenReady**
Another suggestion is: Presentation logic of **ChildFlow** must be done by **ParentFlow**, this gives you reusable Flow which can be presented in different modes from different places.

However, through my example of [RxFlowMemory](https://github.com/Dimentar/RxFlowMemory) I showed the **things not to do**

**Comment by twittemb** [comment]
Hi here,

Can we consider this issue resolved since @Dimentar has provided an example of good practices ?

thanks for your feedback.
