### ISSUE TITLE
UIAlertController Handling

### ISSUE THREAD

**Issue by savage7** [RxSwiftCommunity/RxFlow#51]
I'm starting a new project and I try to use RxFlow 😃

I cant find a simple solution how to best handle UIAlertControllers, without a taste of over engineering my flows. Can you give me some advise how to best handle them?

- Do you create a general Step like "openAlert(title, message, actions)"? This could be implemented in all flows (or some kind of base class).
- Do create a step per alert?
- Do even create steps for alerts or do you just handle alerts in the controllers?
- Do you have a different approach?

Thanks in advance!

**Comment by twittemb** [comment]
Hi @savage7, thanks for reaching out.

Although we could consider a dedicated func in a some kind of base flow to build a UIAlertController, I think displaying an Alert box is not really part of navigation ... it's like displaying or not an hidden View in a ViewController to me.

To keep it simple and stupid, I think I would handle the UIAlertController in the ViewController itself.

It would be different if it was about displaying a rich "popup" screen that could be mutualized between several screens ... in this case I would have done something more generic.

Do you see my point ?

**Comment by savage7** [comment]
Thank you for you answer!

Yes I understand your point and I share your opinion, the simplest solution is to do it in the ViewController.

I thought it would be good to move all the present/dismiss calls out of the ViewControllers but in the end  that to complicated for the benefit...
