### ISSUE TITLE
NoneStepper question

### ISSUE THREAD

**Issue by mfcollins3** [RxSwiftCommunity/RxFlow#53]
Hi. I just recently started looking at RxFlow and have a question. I see that in RxFlow/Stepper.swift that there is a class named `NoneStepper`, but that class is not public. I had a case tonight where I wanted to pass an empty `Stepper` object. I don't see that class being used anywhere in the framework. It seems weird to be private to the framework and not exposed. Is it meant to be public?

Great framework. Thanks for contributing it to the community.

**Comment by twittemb** [comment]
Hi @mfcollins3 
thanks for your feedback.
What is your need to pass an Empty stepper ? because if you pass an empty stepper it means that you consider you don't want to have any further navigation for your "presentable". In that case you just have to return a NextFlowItems.none value.
Does it help ?

**Comment by mfcollins3** [comment]
I hadn't thought of `NextFlowItems.none` when I was looking at it. 

As I'm developing my app, I'm putting in RxFlow incrementally and I wanted to display my view controller without having anyplace else for it to go until I build the next part, if that makes sense. That's why I was looking at the empty stepper.

Thanks for your reply.

**Comment by twittemb** [comment]
@mfcollins3 
No problem.
Take a look at the demo app ... there is almost every kinds of navigation there !

**Comment by SeRG1k17** [comment]
@twittemb, @mfcollins3  meant that he would like to use a **NoneStepper**
```swift
/// a Stepper that triggers NoStep.
final class NoneStepper: OneStepper {
    convenience init() {
        self.init(withSingleStep: NoneStep())
    }
}
```
becase he want this:
```swift
return .one(flowItem: NextFlowItem(nextPresentable: firstFlow,
                                           nextStepper: NoneStepper()))
```

Easy but, not a good solution:
```swift
return .one(flowItem: NextFlowItem(nextPresentable: firstFlow,
                                           nextStepper: OneStepper(withSingleStep: NoneStep())))
//...
//Copy internal struct from RxFlow
struct NoneStep: Step {
}
```
Proposals: 
- make **NoneStepper** as public.
- or make OneStepper open, for inheritance outside module.
