### ISSUE TITLE
Nested subscription

### ISSUE THREAD

**Issue by dangthaison91** [RxSwiftCommunity/RxFlow#6]
As RxSwift tips, nesting subscription should be avoided. While implementing `CompositeStepper` PR #5, I see you are triple subscribed in `Coordinator.swift` and it leads to a crash. I'm refactoring this function, so I open an issue to open discuss if you have any ideas?

https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Tips.md

**Comment by twittemb** [comment]
Hi @dangthaison91 

Thanks for your feedback. I totally agree on the nested subscriptions. We have to find a way to flatten this whole subscriptions chain.

I will work on that in a dedicated branch and come back to you later. I will try to use flatmap fix this issue. If you have better ideas, feel free to comment this thread.

For the CompositeStepper feature, in your case a workaround could be to return an array of Flowable like that in your Flow:

```swift
return ([Flowable(nextPresentable: myViewController, nextStepper: myViewController),
                 Flowable(nextPresentable: myViewController, nextStepper: myViewModel)])
```

This way, the Coordinator will listen to both of these Stepper according to the same Presentable display state.

What do you think about that ?

**Comment by dangthaison91** [comment]
@twittemb Thanks for your suggestion, I think workaround will work.

I just made a quick refactoring to remove nesting subscription follow your implementation. But I don't really happy with it, maybe we have to change the code flow:
```Swift
    /// Launch the coordination process
    ///
    /// - Parameter stepper: The Stepper that goes with the Flow. It will trigger some Steps at the Flow level
    func observeStepper(_ stepper: Stepper) {
        self.steps.asObservable()
            .do(onNext: { [unowned self] step in
                self.delegate.willNavigate(to: self.flow, with: step)
            })
            .flatMap { [unowned self] step -> Observable<[Flowable]> in
                let flowables = self.flow.navigate(to: step)
                self.delegate.didNavigate(to: self.flow, with: step)
                return Observable.just(flowables)
            }
            .do(onNext: { [unowned self] flowables in
                flowables.filter { $0.nextPresentable is Flow }.forEach {
                    self.delegate.navigateToAnotherFlow(withFlowable: $0)
                }
            })
            .flatMap { flowables -> Driver<Step> in
                let nextSteps = flowables
                    .map { return $0.nextPresentable is Flow ? nil : $0 }
                    .flatMap { $0 } // filter nils
                    .map { flowable -> Driver<Step> in
                        // the Flowable's next presentable is not a Flow, it can be processed at the FlowCoordinator level
                        if  let nextPresentable = flowable.nextPresentable, let nextStepper = flowable.nextStepper {
                            let nextStep = nextStepper.steps
                                .pausable(nextPresentable.rxVisible.startWith(true)).asObservable()
                                .asDriver(onErrorJustReturn: NoStep())
                            return nextPresentable.rxFirstTimeVisible.asDriver(onErrorJustReturn: Void()).flatMap { _ in nextStep }
                        } else {
                            return Driver<Step>.never()
                        }
                }
                return Driver.merge(nextSteps)
            }
            .do(onSubscribed: { [weak self] in
                self?.flow.flowReadySubject.onNext(true)
            })
            .asDriver(onErrorJustReturn: NoStep())
            .drive(onNext: { [unowned self] (step) in
                self.steps.onNext(step)
            })
            .disposed(by: disposeBag)
        
        // we listen for the Warp dedicated Weftable
        stepper
            .steps
            .pausable(self.flow.rxVisible.startWith(true))
            .asDriver(onErrorJustReturn: NoStep())
            .drive(onNext: { [unowned self] (step) in
                // the Flow's Stepper fires a new Step (the initial Step for exemple)
                self.steps.onNext(step)
            })
            .disposed(by: flow.disposeBag)
    }
```

**Comment by twittemb** [comment]
Hi @dangthaison91 
Thanks for you code. I'm working on this refactoring on my side. I'll keep you informed when this is OK.
I leave this issue open until the work is merged so we can discuss about this.

**Comment by dangthaison91** [comment]
@twittemb  I think you will have more ideas on this caused you are the creator. I already integrate into my project so really looking forward to this. If you need any help, please ask.

Composite Steppers on PR #5 work with the code above. I will check again once this issue is solved. Please leave it open.

**Comment by twittemb** [comment]
Hi @dangthaison91 

I have made a PR about nested subscriptions. You are a reviewer so you can give me your feedback.

PR -> https://github.com/RxSwiftCommunity/RxFlow/pull/12

Thanks.

**Comment by twittemb** [comment]
The PR has been merger.
