### ISSUE TITLE
Pattern for unit testing flows?

### ISSUE THREAD

**Issue by mfcollins3** [RxSwiftCommunity/RxFlow#61]
I'm using RxFlow in my app, and I'm admittedly behind on my unit test plans. I'm trying to catch up and create unit tests for my flows. When creating a unit test for the `Flow.navigate(to:)` method though, I'm seeing that there's no good way to really test the result. I can test whether the `NextFlowItems` result is `one`, `none`, or `many`, but there's no way to test to validate that the right flow or view controller is being returned because the members of `NextFlowItem` are not public.

Is there a recommended way for building unit tests involving `NextFlowItem` and `NextFlowItems`?

**Comment by twittemb** [comment]
Hi @mfcollins3 

Give it a try on the develop branch. I have set nextPresentable and nextStepper public (read only)

Moreover, have you tried to use Coordinator.rx.did/willNavigate Observables to monitor which flow/step is being coordinated.

**Comment by twittemb** [comment]
@mfcollins3 hi, any update ?

**Comment by twittemb** [comment]
Great news @mfcollins3.

Thanks for using RxFlow 👍

**Comment by farshadtx** [comment]
Any chance to release that commit soon?

**Comment by twittemb** [comment]
Hi @farshadtx 

Release 1.5.0 will embed this. It will be out tonight.

**Comment by twittemb** [comment]
@farshadtx 

release 1.5.0 is out !

**Comment by farshadtx** [comment]
Thanks.
