### ISSUE TITLE
Few source of stepper...

### ISSUE THREAD

**Issue by edon2005** [RxSwiftCommunity/RxFlow#62]
Hi Guys,

Thanks for your framework!
And I am a little confused how to solve a problem:
I have a MainViewController with child view controller inside.
Also the main ViewController have a top left button clicking on showed LeftMenu.
the problem is next: user can click on buttons inside child view controller that should set next step,
and user can click on buttona inside left menu, that should set the same next step as inside child view controller. 
On clicking button the information should changed in childviewcontroller. No metter where button was clicked.
I set in code next string: 
```
return NextFlowItems.multiple(flowItems: [
            NextFlowItem(nextPresentable: modulesFlow, nextStepper: leftMenuViewController),
            NextFlowItem(nextPresentable: modulesFlow, nextStepper: OneStepper(withSingleStep: QRStep.module(0))),
            ]
        )
```
But with such code clicking inside children view controller works good, but clicking on buttons in Left menu rxflow did not see. How can I achieve needed result?

Thanks.

**Comment by twittemb** [comment]
Hi @edon2005 

Thanks for you feedback. Is it possible to have a look at your code or some parts of your code ?

**Comment by edon2005** [comment]
@twittemb First of all BIG thanks for answer. 

I used your comment and change my code. At first it did not worked. When I set OneStepper as first element - it began to work. So 2nd element did not called. 1st element of CompositeStepper - called. I dont know why. Maybe it should so.

Right now my code looks like:
``
class DashboardFlow: Flow {
    private lazy var rootViewController: UINavigationController = {
        let navigationVC = UINavigationController()
        navigationVC.isNavigationBarHidden = true
        return navigationVC
    }()

    private lazy var appConfiguration = container ~> AppConfiguration.self
    private var container: Container!

    init(container parent: Container) {
        self.container = makeContainer(parent: parent)
    }

    private func makeContainer(parent: Container) -> Container {
        return Container(parent: parent) { container in
        }
    }
}

extension DashboardFlow {
    var root: Presentable {
        return rootViewController
    }

    func navigate(to step: Step) -> NextFlowItems {
        guard let step = step as? QRStep else { return NextFlowItems.none }

        switch step {
        case .dashboard:
            return navigationToMainScreen()
        default:
            return NextFlowItems.none
        }
    }
}

extension DashboardFlow {

    private func navigationToMainScreen() -> NextFlowItems {
        let leftMenuViewController = LeftMenuViewController(modules: appConfiguration.menuModules,
                                                            config: appConfiguration.general)
        let leftMenuNavigationController: UISideMenuNavigationController = {
            let vc = UISideMenuNavigationController(rootViewController: leftMenuViewController)
            vc.menuWidth = leftMenuViewController.leftMenuWidth
            vc.isNavigationBarHidden = true
            vc.leftSide = true
            return vc
        }()

        let modulesFlow = ModulesFlow(container: container)

        Flows.whenReady(flow1: modulesFlow) { [unowned self] (root) in
            let vc = DashboardViewController(appConfiguration: self.appConfiguration,
                                             leftMenuViewController: leftMenuNavigationController,
                                             moduleViewController: root)
            self.rootViewController.setViewControllers([vc], animated: false)
        }

        return NextFlowItems.one(flowItem:
            NextFlowItem(nextPresentable: modulesFlow, nextStepper: CompositeStepper(steppers: [OneStepper(withSingleStep: QRStep.module(0)), leftMenuViewController])))
    }

``

**Comment by twittemb** [comment]
Hi @edon2005 

I think there is 2 ways to address you problem:

1st solution:

Having a left menu is a little bit like doing a master/detail. Just take a look at what I did in the Settings part of the demo application in the Repo. The master view (your left menu) is declared as a Stepper, and the Detail view (your Child view controller) is declared as a Stepper as well and in the first navigate(to:) function you return something like that:

```swift
return NextFlowItems.multiple(flowItems: [NextFlowItem(nextPresentable: leftMenuViewController, nextStepper: leftMenuViewController),
                                                  NextFlowItem(nextPresentable: childViewController, nextStepper: childViewController)])
```

what it means is that both the menu and the child view will be able to trigger new Steps inside the Flow. The constraint here is that you have to implement the leftMenu and the child view controller inside the same Flow (and not the DashboardFlow + ModulesFlow).

2nd solution:

If you really want to have you leftMenuViewController declared outside the ModulesFlow, you should have something like that in your DashboardFlow:

```swift
return NextFlowItems.one(flowItem:
            NextFlowItem(nextPresentable: modulesFlow, nextStepper: CompositeStepper(steppers: [OneStepper(withSingleStep: QRStep.module(0)), leftMenuViewController]))
```

and also in the first navigate(to:) of your ModulesFlow, something like that, considering that your childViewController is also a Stepper:
```swift
return NextFlowItems.one(flowItem:
            NextFlowItem(nextPresentable: childViewController, nextStepper: childViewController)
```

Keep in mind that your Stepper should probably not be your ViewControllers but some kind of ViewModel or Presenter, for a better separation of concerns.

For the question about the Flow lifecycle: For now, a Flow dies when you explicitly returns a .end NextFlowItems. It could be modified if you propose a good implementation ... feel free to make a PR 👍.

Hope this helps.

**Comment by edon2005** [comment]
Thank you very much for answer and your advices.
Regarding Flow's lifecycle - maybe it needs to kill flow when parent flow is triggered without special NextFlowItems.one(triggerParentFlow) ?

**Comment by twittemb** [comment]
Hi @edon2005 

May I close this issue ?

**Comment by edon2005** [comment]
Yes, Thanks you :)
