### ISSUE TITLE
Passing needed dependencies as Step enum associated values

### ISSUE THREAD

**Issue by Jauzee** [RxSwiftCommunity/RxFlow#69]
I was trying this library and was thinking about app flows and DI, so I have a question: is it bad practice to declare enum cases with associated values (view models) to pass them from Steppers? It will retain the most recent step's value because BehaviorRelay will hold it, but maybe it can be changed somehow, if the idea isn't bad, if it is please explain why.

**Comment by twittemb** [comment]
Hi @Jauzee 

I am not sur what you want to do ? Using enum associated values is great and recommended to pass data from one Flow to another (a next Flow or a parent Flow).

Indeed if your ViewModel is also your Stepper, passing it as a parameter of a Step which will be sent to a BehaviorRelay could be risky ... As a Stepper MUST be a class we have to deal with shared references.

I like to pass really tiny pieces of information between Flows (like IDs or little data structures) and I let the next Flow handle the DI of ViewModels.

Can you share some snippets of code so we can dig into that ?

**Comment by twittemb** [comment]
Hi @Jauzee 

any updates on this ?

**Comment by Jauzee** [comment]
At the beginning it seemed as a good idea to pass a ViewModel from a Stepper, i.e. if we have a FeedViewModel as a Stepper and we want to open FeedDetailsViewModel, I wanted to go to .feedDetailsStep(FeedDetailsViewModel), but then I realized that it's better to construct FeedFlow with all the needed dependencies inside of it, so it'll be more like a _FeedFactory_ and on each step it will resolve dependencies and pass into ViewModels.

@twittemb thanks for your help!
