### ISSUE TITLE
Subscribe step

### ISSUE THREAD

**Issue by edon2005** [RxSwiftCommunity/RxFlow#70]
Hi guys,

From what I understand looking at code of RxFlow, step will be subscribed when viewController didAppear. 
Why rxflow dont do it earlier, for example on viewWillAppear or more earlier? 

Thanks.

**Comment by twittemb** [comment]
Hi @edon2005 

Because once the Stepper is subscribed, if it triggers a first Step before the View HAS appeared It could ask the Flow to display another ViewController on top of something that hasn't been displayed yet ... I'm not sur if UIKit would appreciate it ! but it is something we can challenge for sur.

Have you tried to change it ?

**Comment by edon2005** [comment]
Hi @twittemb,

Yes I have change it for my project. And it works perfectly. 
Because I just need such way, before showing one ask to show another screen. 
For example: I show a viewController with pushing, and blocking the access to the viewController with presenting second viewController with offering user to get access. the secondViewController has faded transparent background to show what user could get after getting access.

**Comment by twittemb** [comment]
Hi @edon2005 

Can you do a PR so I can review it and eventually put it in the next release plz ?

thanks.

**Comment by edon2005** [comment]
Hey, I did. 

https://github.com/RxSwiftCommunity/RxFlow/pull/78

**Comment by twittemb** [comment]
thanks ... PR merged.

**Comment by edon2005** [comment]
Not at all :)

**Comment by twittemb** [comment]
Hi @edon2005 

It seems that the modification you've made in this PR https://github.com/RxSwiftCommunity/RxFlow/pull/78 brings some problems for some users.

Do you think your app could work without those changes ? for instance by triggering a second step (to display you second viewController) right after the first one ?

**Comment by edon2005** [comment]
HI, Yes, it seems my commit destroyed functionality for some users. Really sorry for this. 
In my application it would work but user will see first viewcontroller as usual, and then second viewcontroller will appear with fading first viewcontroller in a second. SO it can be ok but not as perfect as before :) 
For me it is not a problem if you revert commit. I can just keep this part of your framework modified in my project while dont get a bug like guys get.
For me it is really interesting why subscription for stepper did not work in their case. because in few my applications  it works as usually. And do you have any changes in working of your projects?

**Comment by twittemb** [comment]
Thanks for the feedback @edon2005 

I've reverted the commit in the version 1.6.1

We will try to figure out a way to implement your feature for sure.
