### ISSUE TITLE
How to hide a tab bar when using RxFlow?

### ISSUE THREAD

**Issue by BirdyF** [RxSwiftCommunity/RxFlow#72]
Hi, 

I am trying to use RxFlow (I am new to RxSwift too) for a new project and I would like to hide a tab bar. The only solution I found so far is to have a global variable like  
let DashboardRootViewController = UITabBarController()

then DashboardRootViewController.tabBar.isHidden = true

Is there a nicer way to do it?

**Comment by twittemb** [comment]
Hi @BirdyF 

I'm not a UIKit expert but it looks like the right way. But I'm curious about why you would have to make a UITabBarController if you hide its TabBar ?

**Comment by BirdyF** [comment]
Hi @twittemb,

Unfortunately I am not  UIKit expert too! I would like to hide the bar because I want to use all the screen to display a video and then when the user tap the screen show again the tab bar.

**Comment by pavlodavydiuk** [comment]
Hi @BirdyF,

You can do it easy by setting `hidesBottomBarWhenPushed` property when you push next view controller.

Sample:
`nextViewController.hidesBottomBarWhenPushed = true`
