### ISSUE TITLE
How does RxFlow navigation between coordinators works?

### ISSUE THREAD

**Issue by felixsolorzano** [RxSwiftCommunity/RxFlow#73]
It's pretty common that the user navigates back in a UINavigationController by gesture, so I'd like to know if you already support it?

**Comment by twittemb** [comment]
Hi @felixsolorzano 

RxFlow does not interfere with UIKit built-in back mechanism inside a navigation stack.

It is important to let UIKit deal with that on its own.

What is your concern about that ?

**Comment by felixsolorzano** [comment]
I'm a bit confused on how does this library handle references and instances, specially when navigating back in the navigation stack and from one flow to another, how does this work?

I mean, lets say we have a **HomeFlow** and a **SettingsFlow** after opening _settings_ and going back to _home_ ho does RxFlow release the SettingsFlow instance? Or what do I have to do in order to release it, I know there's a `endFlowCoordinator` in your `Coordinator` class but there's no example of that in the Demo app.

**Comment by twittemb** [comment]
There are 2 cases when Flows are unretained:

- its root view controller is explicitly dismissed
- you trigger a .end NextFlowItems

Is it clear enough for you ?

**Comment by twittemb** [comment]
Hi @felixsolorzano 

Is it ok with you to close this issue ?

**Comment by SeRG1k17** [comment]
@twittemb Same issue. Back(pop) Pan gesture recognizer in navigationController not working. You can see this bug in the demo app.
Watchlist -> MovieDetail. Try to go back with a pan gesture from the left edge of the screen.

**Comment by SeRG1k17** [comment]
@felixsolorzano Its simulator bug. Just restart him.

**Comment by felixsolorzano** [comment]
Thanks!
