### ISSUE TITLE
How could I implement a custom action for a UITabBarItem?

### ISSUE THREAD

**Issue by felixsolorzano** [RxSwiftCommunity/RxFlow#74]
I reviewed the code from *RxFlowDemo*, but there's no example of how to handle a custom action from a UITabBarController.

To handle a custom action we commonly implement the following function from `UITabBarControllerDelegate`:

```swift

    func tabBarController(_ tabBarController: UITabBarController, shouldSelect viewController: UIViewController) -> Bool {
        
        if viewControllers?.index(of: viewController) == 2 {
            // TODO: Open camera from TabCoordinator
            return false
        }
        
        return true
    }

```

How would this be done in RxFlow?

**Comment by twittemb** [comment]
You could do this in multiple ways:

- your stepper could also be your tabBarController's delegate and it could call "self.steps.accept(Steps.needCamera)" to trigger the navigation.
- if your tabBarController's delegate is also your TabBar ViewController and this ViewController has a ViewModel registered as a Stepper you could call a "cameraClicked" function on your ViewModel and this function could call "self.steps.accept(Steps.needCamera)" to trigger the navigation

**Comment by felixsolorzano** [comment]
Could it be possible for you to provide code example of the _most_ appropriate way of doing it following your library style?

**Comment by twittemb** [comment]
Hi @felixsolorzano 

I would do something like I did in the demo app for the Settings button in the Navigation Bar of the first tab. This Settings button is handled by the Stepper of the WishlistFlow.

Take a look at the WishlistStepper inside the WishlistFlow.

**Comment by twittemb** [comment]
Hi @felixsolorzano 

Have you looked at the demo app ?

**Comment by twittemb** [comment]
Hi @felixsolorzano 

May I close this issue ?

**Comment by felixsolorzano** [comment]
As you said, the stepper could be the tabBarController's delegate, the only thing I'm kinda disagree is that it's a non rx way to do it.
