### ISSUE TITLE
How to coordinate more than 3 Flows?

### ISSUE THREAD

**Issue by PleaseDont** [RxSwiftCommunity/RxFlow#8]
How to coordinate more than 3 `Flows` when using a `UITabBarController` with 4 or 5 `tabBars`?

I tried to overwrite the `Flows.whenReady` using `extension`, but it thrown error `'rxFlowReady' is inaccessible due to 'internal' protection level`.

**Comment by twittemb** [comment]
Hi @PleaseDont

I tried to implement the whenReady function in the same manner than Observable.zip or Observable.combineLatest. For more than 3 Flows we have to modify the Flows code to add function that takes 4, 5, ... Flows and maybe add a function that takes a collection of Flows. If you wish you can do a PR or if you are not comfortable with that let me know so I can do it myself.

**Comment by PleaseDont** [comment]
thx @twittemb 
I'm still a rookie in Swift&iOS, but I will try.😅

**Comment by twittemb** [comment]
@PleaseDont if you do so, please do your PR on the develop branch.

Do a first draft and I will help you if you are stuck :-)

**Comment by tomisacat** [comment]
@PleaseDont I've added a function satisfied your need, feel free to check it out : )

**Comment by PleaseDont** [comment]
@tomisacat Thank you so much :-)

**Comment by twittemb** [comment]
I will merge this PR tomorrow 👍

**Comment by twittemb** [comment]
@tomisacat @PleaseDont I close this issue since the PR https://github.com/RxSwiftCommunity/RxFlow/pull/9 has been merged.

Thanks.
