### ISSUE TITLE
RxReduce + RxFlow

### ISSUE THREAD

**Issue by Alex293** [RxSwiftCommunity/RxFlow#80]
Is there a way to combine RxReduce + RxFlow to get something like ReSwift ?
Having both well integrated would really enhance Rx project in my opinion.

**Comment by twittemb** [comment]
Hi @Alex293 

This is exactly the idea behind these 2 repos. In my personal projects I combine RxFlow and RxReduce to have a full reactive unidirectional data flow.

Perhaps some day I will publish some examples, If I get more time :-)

**Comment by MortMerr** [comment]
@twittemb have you ever checked ReactorKit?

**Comment by MortMerr** [comment]
@twittemb i don't want to create new issue just for one question, so i will ask here.
Have you ever thought about how working with objc_runtime from swift code (associated object) will affect performance?

**Comment by twittemb** [comment]
Hi @MortMerr 

Nop ! never checked ... do you have a feedback on this ?

**Comment by twittemb** [comment]
Hi @MortMerr 

Indeed asociated objects are not mandatory. I just wanted to avoid the developers to have to declare a BehaviorRelay each time they would declare a Stepper for instance because Stored properties are not handled by protocol extensions.

This is something that is "convenient" but not necessarily a "good practice" to use this mechanism.

For now I don't want to change my implementation but if you have suggestions I'm opened to it.

**Comment by twittemb** [comment]
Hi @MortMerr 

Is it ok to close this issue ?

**Comment by AlexisQapa** [comment]
Yes it is. Thought I'd be interested if you got any small example with the navigation state put into the store.

**Comment by MortMerr** [comment]
@twittemb of course, fell free. I don't like asociated objects, and the only suggestion from me - replace them on simple protocol variable

**Comment by freak4pc** [comment]
Just as an afterthought - this can possibly be replaced with a protocol with default extension implementation that actually works with associated object. If a developer wants to avoid Associated Objects they can re-implement the protocol to have their own bags, etc.

**Comment by twittemb** [comment]
Thanks @freak4pc. Will try that soon.

**Comment by freak4pc** [comment]
BTW I'm a fan of Associated Objects :) But this is for other people in this case. 
It's a minor "nuisance" to clean up the API real nicely.

**Comment by twittemb** [comment]
Hi there,

The use of `Associated Objects` has been greatly reduced in RxFlow 2.0.0.

Since there is no more activity on this issue, I will close it.

Feel free to reach out if you have more questions.

Thanks.
