### ISSUE TITLE
App Coordinator Setup

### ISSUE THREAD

**Issue by chriskilpin** [RxSwiftCommunity/RxFlow#87]
Hi @twittemb

I have a setup very similar to the example project. I have a UITabBarController as my root view controller which has some of its own child flows. When the app starts up I need to check if the user is logged in and display login. The difference is I want to present the login view controller as a form sheet over my tab bar and not swap out the root view controller. I have tried calling step.accept one after the other but the second call seems to overwrite the first. Is there a better way of structuring things to achieve this functionality? 

Thanks in advance.

**Comment by twittemb** [comment]
@chriskilpin 

I tried to make something really quickly ... it should help -> https://github.com/RxSwiftCommunity/RxFlow/tree/demo/popupLogin

thanks.

**Comment by chriskilpin** [comment]
Hi @twittemb

We had something similar on our end with a timer but your implementation of calling checkLogin inside the stepper from the flow complete block is definitely better. 

Thanks for the help it is much appreciated.
