### ISSUE TITLE
Different behaviour depending on setViewControlelrs( [vc], animated: [true|false])

### ISSUE THREAD

**Issue by mariovoelker** [RxSwiftCommunity/RxFlow#88]
Hey, first of: Stellar Project!

I have the following flow
-> [.loading] -> Loading 
-> [.loadingComplete] -> DisplayData 
(User clicks refresh)
-> [.loading] -> Loading 
-> [.loadingComplete] -> DisplayData

I ran into an issue where going through the same flow behaves different the first go round. Up until User clicks refresh everything is displayed fine. 
Now if I click refresh I expected everything to happen just as before - which it did not. NavigateTo was not called for the second .loadingComplete Step. So the Loading screen persisted.

As I read in a different post, the presentable needs to be displayed. 
I changed my code from
> self.rootViewController.setViewControllers([appLoadingVC], animated: **true**)

to

> self.rootViewController.setViewControllers([appLoadingVC], animated: **false**)

before I call 

> return .one(flowItem: NextFlowItem(nextPresentable: appLoadingVC, nextStepper: appLoadingVC.appLoadingViewModel!))

which actually led to the desired outcome.

I am not sure if I you can even help me here but there seems to be something funky going on with the timing and thus the first time the ViewController is displayed on time. The second time - not so much.

Do you have any thoughts on the matter? Is that expected behaviour? 

Cheers,
Mario

**Comment by twittemb** [comment]
Hi Mario

What is your version of RxFlow ?

**Comment by mymymario** [comment]
I am using RxFlow version 1.6.1

**Comment by sree127** [comment]
We are currently facing a similar issue as well. I can share more insights in a new issue

**Comment by sree127** [comment]
OK. Fixed it after setting `allowStepWhenNotPresented` to true :)
