### ISSUE TITLE
How could I avoid rewriting funcs to open a specific controller?

### ISSUE THREAD

**Issue by felixsolorzano** [RxSwiftCommunity/RxFlow#90]
I've got a controller that is opened from different flows, how could I avoid copy/paste the same code across flows? I know it depends on the app navigation design, but for this case it's very difficult to design it a way it would need repeating the step.

Think about facebook posts, you can open a post detail from the feed or from a profile, how could you avoid repeating the code in the `FeedFlow` and the `ProfileFlow`?

**Comment by twittemb** [comment]
Hi @felixsolorzano 

One way of doing this could be:
- define 1 protocol "HasDetailNavigation" with a "func navigateToDetail(from: UIViewController) -> NextFlowItems"
- extend that protocol to have a default implementation of this function
- make the some of the Flows conform to this protocol

That way these Flows will all have access to "navigateToDetail(from:)"

Is this something doable in your case ?

**Comment by felixsolorzano** [comment]
Yeah, that works great!, only one question I pass the navigation controller in the func so that it could push from there, I'm not that sure if it would be the right way:

```swift

protocol HasXNavigation {}

extension HasXNavigation {
    
    func controllerX(type: DatType, from navigate: UINavigationController) -> NextFlowItems {
        
        ...
        
        // RxFlow
        let stepper = CompositeStepper(steppers: [
            controller,
            iGDataSource
            ]
        )
        
        let item = NextFlowItem(
            nextPresentable: controller,
            nextStepper: stepper
        )
        
        navigate.pushViewController(controller, animated: true)
        
        return NextFlowItems.one(flowItem: item)
    }
}

```

What do you think?

**Comment by twittemb** [comment]
Yes if can be great.

**Comment by felixsolorzano** [comment]
Thanks, I'll close this, your proposal worked for me.
