### ISSUE TITLE
What is the proper way to do back (navigation controller.popViewController) ?

### ISSUE THREAD

**Issue by sprhawk** [RxSwiftCommunity/RxFlow#91]
Hi, I'm using RxFlow in my app. But I encounter a weird problem.

 I have a navigation controller with bar hidden, so I need an IBAction to do `navigationController.popViewController`

The app structure is like:

```
App Flow( Dashboard Flow ( Tab1 Flow, Tab2 Flow) )
```

I do navigation inside Tab2 Flow. with `AppStep.moreabout`

```
func navigationToMoreAbout() -> NextFlowItems {
        let moreaboutViewController = MoreAboutViewController.instantiate()
        moreaboutViewController.hidesBottomBarWhenPushed = true
        self.rootViewController.pushViewController(moreaboutViewController, animated: true)
        return .none
    }
```

Currently I do AppStep.moreaboutDone to pop:

```
case .moreaboutDone:
            self.rootViewController.popViewController(animated: true)
            return .none
```

when I again do step AppStep.moreabout, the NavigationController push twice the child view controller ,  if I go back and do again, it will push 3 times, and so on.

How it is happen ?

I saw there is no popViewController inside Demo, it seems using a default back action by navigation Controller, is there any differences?

When I debugged it, after

```
case .moreaboutDone:
            self.rootViewController.popViewController(animated: true)
            return .none
```

the navigation controller step remains only one root view controller

but when I do ` .moreabout` again , the 

step `.moreabout` is called twice

**Comment by sprhawk** [comment]
Find a bug in my View Controller

**Comment by anhdle14** [comment]
@sprhawk could you tell me more about the bug, i got the same issue and it is triggering me... Still don't know how to solve it yet.

The only work around i got is to .popViewController

**Comment by sprhawk** [comment]
I just use another step, and in navigate(step:) call pop, and return .none

**Comment by anhdle14** [comment]
Could you elaborate more? A sample of the code would be good
