### ISSUE TITLE
Memory leak when ending .multiple flow

### ISSUE THREAD

**Issue by wberger** [RxSwiftCommunity/RxFlow#92]
My app currently has a serious memory leak and I was able to reproduce it in a slightly modified version of the demo app.

It is demonstrated in this branch:
https://github.com/wberger/RxFlow/tree/test/multiple_leak

The relevant files are:
RxFlowDemo/RxFlowDemo/Flows/AppFlow
RxFlowDemo/RxFlowDemo/Flows/DashboardFlow
RxFlowDemo/RxFlowDemo/Flows/WishlistFlow

I added a "Logout" button to the wishlist. Hitting this button will trigger a step in `WishlistStepper`, which in turn ends the `WishlistFlow`. This ends the parent (= `DashboardFlow`) and triggers a navigation to the `OnboardingFlow` from within the `AppFlow`.

The problem is that only `WishlistFlow` reaches deinit, while `DashboardFlow` and `WatchedFlow` don't. As a result the whole UITabbarController and all contained ViewControllers are kept.

Reentering the `DashboardFlow` from onboarding creates new instances while the old dashboard flows and view controllers are kept thus creating a potentially huge memory leak.

I had a quick look at the Flow implementations but wasn't able to find the error. But in general, when a flow ends, the ending flow and all sub flows have to be released.

**Comment by anthony-sanchez** [comment]
Same issue here

**Comment by twittemb** [comment]
Hi guys

Very interesting. Thanks for the example. I will work on that ASAP.

**Comment by antgar** [comment]
Same issue here too

**Comment by twittemb** [comment]
Hi guys. Work In Progress.

I'll give feedback soon.

**Comment by twittemb** [comment]
Hi @antgar, @anthony-sanchez, @wberger 

Could you try RxFlow with the develop branch. I've pushed a fix for the memory leaks.

I hope this helps.

**Comment by wberger** [comment]
Thank you, I will try it tomorrow!

**Comment by hampusiggstrom** [comment]
I had the same issue and solved it by the simple but hacky solution to remove all VCs in the tab bar on `.end`. 

The latest commit in the develop branch fixes this issue for me.

Thx!

**Comment by wberger** [comment]
@twittemb Thank you, this fixes the issue!

**Comment by dsk1306** [comment]
I've just tried new fix and it didn't really help me.
I've made a simple project  in which I have an app with onboarding screen and tab bar. I've tried to implement logout flow with throwing .end flow item down to root flow and noticed that not all of my flows (and controller) were deinited. Maybe I just do it wrong? Please, have a look at https://github.com/dsk1306/rxFlow-92 when you have a free time.

**Comment by twittemb** [comment]
@dsk1306 There was an issue with my release. Please try again by reinstalling the v1.6.2.

Thanks.

**Comment by dsk1306** [comment]
@twittemb it did help. Thanks.

**Comment by fatbunboy** [comment]
hi @twittemb, thanks for the fix.  However, I notice this fix is working on Carthage but CocoaPods.
I have same set of code, both are using v1.6.2, but CocoaPods seems still leaking memory.

**CocoaPods:**
https://github.com/fatbunboy/RxFlowTestingPods

**Carthage:**
https://github.com/fatbunboy/RxFlowTesting

**Comment by twittemb** [comment]
Hi @fatfunboy

Thanks for the feedback. I will take a look at that today.

**Comment by twittemb** [comment]
@fatbunboy I've just cloned your repo and gave it a try. I had no issue with memory leak. Have you made a pod update / pod install ?

**Comment by MortMerr** [comment]
@twittemb i also still has this issue (using cocoapods, Rxflow 1.6.2)

**Comment by fatbunboy** [comment]
@twittemb , sorry that I didn't indicate the steps. added Readme and screenshots to 

CocoaPods:
https://github.com/fatbunboy/RxFlowTestingPods

Carthage:
https://github.com/fatbunboy/RxFlowTesting

1. passed on-boarding flow
2. tap logout button on top-left on wishlist flow

it shows DashboardFlow and WishlistFlow are retained by using cocoapods Rxflow 1.6.2

**Comment by twittemb** [comment]
@fatbunboy thanks a lot for your nice feedback.

I will give it a closer look this weekend. Just for the record, have you tried it on the simulator or a real device ?

**Comment by fatbunboy** [comment]
@twittemb. yes tested both on real iPhone and simulator. it does have this issue when using cocoapods Rxflow 1.6.2

**Comment by MortMerr** [comment]
@twittemb please reopen this issue, cause fix is not working/not applied

**Comment by MortMerr** [comment]
Hi @twittemb )
Any updates on that?

**Comment by twittemb** [comment]
Hi there

I'm on vacation for a few days, i will have finally the time to give some love to RxFlow and bring you some answers.

Stay tuned.

**Comment by twittemb** [comment]
Hi there.

I'm working on RxFlow 2.0.0. It brings some breaking changes and a refactor of the memory management. I think it can address the issues that are exposed in this thread.

It would be great if you could give me your feedback on this version (it is currently on the develop branch)

Here are the changes:
- Coordinator has been renamed in FlowCoordinator.
- NextFlowItem and NextFlowItems have been renamed in FlowContributor and FlowContributors.
- The FlowContributors enum entry .end (withStepForParentFlow: Step) has been renamed in .end (forwardToParentFlowWithStep: Step).
- The FlowContributor class has been converted to an enum with the following entries: .contribute(withNextPresentable: Presentable, withNextStepper: Stepper), .forwardToCurrentFlow(withStep: Step) and .forwardToParentFlow(withStep: Step). It allows to unify the way we can contribute to a Flow.
- In an effort to minimize the usage of objc_get/setAssociatedObject, each custom Stepper must declare a stored property steps as a PublishSubject.
- To trigger an initial Step inside a Stepper, an initialStep property has to be implemented. A default implementation is provided by RxFlow if it makes no sense to emit a first Step for your specific use case. This default implementation emits a "void step" that will be ignored by the Flow.
- The reactive step property of a Stepper has been renamed in steps to reflect the plurality of the sequence of steps it can emit.
- FlowCoordinator has been totally rewritten to improve memory management.
- HasDisposeBag has been removed from the project as it was not mandatory in the implementation and is not really related to RxFlow. A similar implementation can be found in NSObject-Rx.
- The RxFlowStep enum is now provided to offer some common steps that can be used in lots of applications. This enum will grow in size over time.
- Some of the old data structure names are still usable but have been explicitly deprecated.

The demo app has been adapted to all those changes.

**Comment by MortMerr** [comment]
@twittemb really fantastic changes. Looking forward to taste it :)

**Comment by twittemb** [comment]
Hi there. Is there anyone who is willing to test RxFlow 2.0.0 before the release ?

**Comment by MortyMerr** [comment]
@twittemb I would like to take a look)

**Comment by twittemb** [comment]
Hi @imtoo

Can you be more precise about your use case and your implementation please?

**Comment by imtoo** [comment]
Hi @twittemb

Sorry, I had a problem with something else. Specifically with implementation of `RxDataSources`.

**Comment by twittemb** [comment]
Hi everyone,

I intend to release RxFlow 2.0.0 in the coming days. Does anybody have encountered issues with the develop branch ?

Thanks.

**Comment by MortyMerr** [comment]
@twittemb haven't found any bugs during testing. Can't wait for version 2.0 :)

**Comment by twittemb** [comment]
Hi guys,

RxFlow 2.0.0 "Enterprise" is released 🎉.

**Comment by twittemb** [comment]
Hi there.

May I close this issue since there hasn't been any comment about memory leaks for a while now ?

Thanks.

**Comment by sulaiman-mlbd** [comment]
@twittemb Having memory leak issue while restarting a flow after visiting on last end. RxFlow version 1.6.0. Did you  fixed memory leak issue on latest release??

**Comment by twittemb** [comment]
@sulaiman-mlbd check the version 2.0.0, memory leaks have been addressed: https://github.com/RxSwiftCommunity/RxFlow/releases/tag/2.0.0
Thanks.
