### ISSUE TITLE
Memory Leaks from profiling

### ISSUE THREAD

**Issue by gordoneliel** [RxSwiftCommunity/RxFlow#93]
I've been using RxFlow for a while now it its amazing! However I noticed a spike in memory when using it, especially with complex flows and dug deeper. I know there are a bunch of issues related to memory leaks but, I noticed that Viewcontrollers never get deallocated, even in the example app, is that normal? None of the deinits for the viewcontrollers get called. Below is a snapshot of the profiler's results.

![screen shot 2018-11-12 at 5 17 03 pm](https://user-images.githubusercontent.com/5516761/48384445-406eec80-e69f-11e8-9cce-364e80cd4a6f.png)

**Comment by twittemb** [comment]
Hi @gordoneliel ,

Could you please try your app with the last develop version of RxFlow ? I've pushed a fix regarding memory leaks related to another issue (https://github.com/RxSwiftCommunity/RxFlow/issues/92) but it could be the same problem than yours.

Thanks.

**Comment by twittemb** [comment]
Any update on this with v1.6.2 ?

**Comment by twittemb** [comment]
Hi @gordoneliel 

From what I see:
- leaks do not appear in a simulator, but I've seen some on a device
- all of them where about UIKit or UIKeyboard.

I would say that this is the demo app that probably leaks.

**Comment by gordoneliel** [comment]
@twittemb Thanks for the followup! I'll close this now.
