### ISSUE TITLE
Any suggested practice for handling remote notification navigation?

### ISSUE THREAD

**Issue by zenghaojim33** [RxSwiftCommunity/RxFlow#95]
I am new to this library and I am thinking about how to deal with navigation by remote notification.  Is there any example shows how to do this elegantly? Thanks.

**Comment by twittemb** [comment]
Hi @zenghaojim33 

Thanks for reaching. Unfortunately I have no example right now.

The way I see it is having an "AppFlow" instance in the apoDelegate that would be driven by an AppStepper. The AppStepper would also be a property of the appDelegate. When receiving a push notif, the appDelegate could ask the AppStepper to trigger the appropriate Step.

It would be up to the appFlow to handle the VC presentation.

**Comment by twittemb** [comment]
Since there is now a function on the FlowCoordinator that can be used to propagate a step from the AppDelegate, I consider this issue closed. Feel free to reopen if you do not agree.
Thanks.
