### ISSUE TITLE
1.6.2 release doesn't contain commit with fix

### ISSUE THREAD

**Issue by dsk1306** [RxSwiftCommunity/RxFlow#96]
I might be wrong (and sorry if I am) but 1.6.2 release's changelog says that it fixes issue with ending multiple flows and I don't see the commit with fix in it.
![screen shot 2018-11-27 at 13 04 08](https://user-images.githubusercontent.com/9428706/49074515-e2690a00-f245-11e8-9140-d636fead76ab.png)

**Comment by twittemb** [comment]
Hi @dsk1306 

I fixed the issue, it should be ok now.

Thanks for your feedback.
