### ISSUE TITLE
100% Programmatically with no Storyboard or Nib, can it be used with RxFlow

### ISSUE THREAD

**Issue by anhdle14** [RxSwiftCommunity/RxFlow#97]
Just like the title, i am working on a project that is 100% written in code, the only Storyboard is the launch screen. RxFlow did a good job on doing the navigation without messing too much with rootViewController. And the ideas of the coordinator is perfect. But from what i have been researching. There are 2 problems i have encountered:
1.  `self.rootViewController.pushViewController()` push to the array of viewControllers, and it won't pop it after hiting `Back` on UINavigationController. 
For example:
> Main (UINavigationController) -> Screen 1 -> Back (to Main) --> Screen 1 --> Back (to the first Screen 1) --> Back (to Main).

2. I saw you have this file: [ViewModelBased.swift](https://github.com/RxSwiftCommunity/RxFlow/blob/a60b6e286fb6c31e2f48bb36530d57e44d956644/RxFlowDemo/RxFlowDemo/Protocols/ViewModelBased.swift) which has: `Self: StoryboardBased & UIViewController`. So is that possible to get the same functionalities (like working on TableView) without Storyboard? Like from this piece of code:
```swift
        let viewController = MovieDetailViewController.instantiate(withViewModel: MovieDetailViewModel(withMovieId: movieId),
andServices: self.services)
``` 
I did only `ViewController()`, it does work but i don't know is that the cause for the first problem or not. 

---
Thank you for this awesome project though.

**Comment by twittemb** [comment]
Hi there.

Can you share your projet (or a part of it) so I can have a closer look ?

BTW ViewModelBased and Storyboard based are just sugar ... You could define a ViewModelBased protocol that has nothing to do with StoryboardBased and should be able to instantiate a VC that conforms to it. I'm using the library Reusable in the demo app just to make it easier to instantiate VC.

**Comment by anhdle14** [comment]
So i tried to create a brand new project with a similar code base, but the UINavigationController.pushViewController work fine. I will try to find the bug by today, if not i will share the whole project with you.

**Comment by anhdle14** [comment]
Ok so i found the bug.

## For short:
1. It was because i use UIButton.addTarget(...)
2. I have multiple buttons register with the same #selection(handleButton(button:))
3. I use `switch`, to fire this piece of code
```swift
button.rx.tap
        .map { AppStep.\(step) }
        .bind(to: self.step)
        .disposed(by: disposeBag)
```
4. So the behavior is not the same if i move this piece of code outside of viewDidLoad scope. 

---
So, is there anyway i could achieve this? or the default navigation with rx.tap can only work if i put it within viewDidLoad scope?
